### PR TITLE
.csproj changed to make the assemblies land in BHoM/Assemblies folder on Debug/Release solution config

### LINKED ISSUE #870: Revit_Toolkit: Make sure that the assemblies land in BHoM/Assemblies folder on Debug/Release solution config
#### Description:
That is needed for CI/CD purposes.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #870

### Test files

Not needed, check if compiles and the files get copied over correctly.

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved following review of the CI/CD stuff - this is good with the changes :smile:

**Review by LMarkowski — APPROVED** [review]
All configs compile and put the assemblies in the right folder. lgtm

**Pull request merged**
