### PR TITLE
Set Copy Local false

### LINKED ISSUE #377: Set "Copy Local" to false
#### Broken rules:

Set "Copy Local" to false to all references

#### Suggestions to restore compliance:

N/A

### PR DESCRIPTION
**Pull request by ZiolkowskiJakub**
### NOTE: Depends on 

N/A
   
### Issues addressed by this PR

Closes #377

### Test files

N/A

### Changelog

- Revit_UI.csproj updated to not copy UI_PostBuild.exe

### Additional comments

N/A

### CODE REVIEW

**Comment by ZiolkowskiJakub** [comment]
Hi @al-fisher, Investigating that now

**Comment by al-fisher** [comment]
Hey @ZiolkowskiJakub - think the issue is the Post-build event in the Revit_UI Project.
Should no longer be calling `UI_PostBuild.exe`

Need to remove 

```
call "$(TargetDir)UI_PostBuild.exe" ..\..\ "$(AppData)\BHoM\Assemblies"
```

**Comment by ZiolkowskiJakub** [comment]
Hi @al-fisher still does not going through AppVeyor

**Comment by al-fisher** [comment]
Yep - looking at it with @FraserGreenroyd now! Thanks @ZiolkowskiJakub

**Comment by ZiolkowskiJakub** [comment]
Works for me

**Comment by ZiolkowskiJakub** [comment]
Please approve so I can merge

**Pull request merged**
