### PR TITLE
UI button layout tweaked

### LINKED ISSUE #1079: Revamp the UI buttons
#### Description:

As discussed with @tiagogrossi, it would be great tweak the button layout a bit to look as follows:

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1079

### Test files

Strictly visual change - open Revit and see if the buttons look good.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by tiagogrossi — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
