### PR TITLE
BH.oM.Physical.Elements.ISurfaces stopped from failing to transform when their Location is not PlanarSurface

### LINKED ISSUE #1001: BH.oM.Physical.Elements.ISurfaces fail to transform when their Location is not PlanarSurface
#### Description:

As in the title.

#### Test file(s):

*#1001-TransformPolySurfaceBug.gh* from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231001%2DTransformPolySurfaceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), to be tested with _FromLink_PullPanelLocation.rvt_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2416

   
### Issues addressed by this PR

Closes #1001

### Test files

- problem-specific files: *#1001-TransformPolySurfaceBug.gh* from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231001%2DTransformPolySurfaceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), to be tested with _FromLink_PullPanelLocation.rvt_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- general test files: _FromLink_PullWallFloorRoofLocation.gh_ with _FromLink_PullPanelLocation.rvt_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### Changelog

- `BH.oM.Physical.Elements.ISurfaces` stopped from failing to transform when their Location is not `PlanarSurface`

### Additional comments

The issue mentioned in the header of this PR is 99% covered by https://github.com/BHoM/BHoM_Engine/pull/2416. This PR is building on top of it, by eliminating the edge case `NullReferenceException` that may occur, totalling with (hopefully) fairly robust behaviour.

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Generally looks good to me. All panels are being pulled correctly.

One strange thing noticed in the test file. Four panels ale lost by grasshopper's Region Difference component (highlighted in green), despite looking good on pull. 
image

It shouldn't block this PR but might be worth investigating.

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Pull request merged**
