### PR TITLE
Handle null exception when querying unloaded links

### LINKED ISSUE #1450: Null exception when querying unloaded links
#### Description:

Revit links return null on GetLinkDocument() if they aren't loaded. This raises an exception in the current code:

https://github.com/BHoM/Revit_Toolkit/blob/1684a74a385683b5f2c8e1ae96822da363896c16/Revit_Core_Engine/Objects/ActiveViewVisibilityContext.cs#L102-L108

image

#### Steps to reproduce:

Run `ElementIdsByVisibleInActiveView` in a model with unloaded links and you'll get the error.

https://github.com/BHoM/Revit_Toolkit/blob/930ddd363be9efbf49e0fbca3c8224771e34deaf/Revit_Core_Engine/Query/ElementIds/ElementIdsByVisibleInActiveView.cs#L40

image

#### Expected behaviour:

We need to handle the null exception.

### PR DESCRIPTION
**Pull request by vietle-bh**
### Issues addressed by this PR

Closes #1450 

I added the null handler.

### Test files

Given the PR's scope, code review should be enough?

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 21355996787

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by vietle-bh** [comment]
Thans @FraserGreenroyd 😉 
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
> Thanks @FraserGreenroyd 😉 @BHoMBot check ready-to-merge

image

**Pull request merged**
