### PR TITLE
Revit_Toolkit - Issue 222 - OpeningPanelCurve

### LINKED ISSUE #222: Revit_Toolkit: Wrong Pull for PaneCruve Openings
If I pull Revit Edges all is correct
image

however when we pull BuildingElement  - PanelCurve this is wrong
image

I believe this is related to Issue I logged, so we should solve Revit and see if we should progress or close these issues:
https://github.com/BHoM/XML_Toolkit/issues/172
https://github.com/BHoM/BHoM_Engine/issues/773

Test attached
[PullSelectionAndBuildingElements_rooflight.zip](https://github.com/BHoM/Revit_Toolkit/files/2791439/PullSelectionAndBuildingElements_rooflight.zip)

### LINKED ISSUE #230: Revit_Toolkit: Rooflight problem with PanelCurve
Current Rooflight geometry not correctly recognized in BuildingElement - Panel Curve
image

### LINKED ISSUE #233: Revit_Toolkit: Wrong Opening Dimension on Tilted Wall
Opening Dimension of angled wall does not match - when we pull with edge method

image

### PR DESCRIPTION
**Pull request by ZiolkowskiJakub**
### Issues addressed by this PR
Closes #222
Fixed #230
Closes #233 

### Changelog
Fix for Environmental Opening PanelCurve pull

### CODE REVIEW

**Comment by ZiolkowskiJakub** [comment]
Closes #231

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub  
1. number of elements are now fixed ...
2. dimension is now modified on this tilted wall.. 
image

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak 
thank you for testing. This Pull request and Issue is about pulling BuildingElements. Pushing Windows is recorded here: #215, #214 and for Doors here: #213 

Please approve this pull request if BuildingElements are **pulled** correctly.

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub ok I run again and still behave the same way ...please can you run on my example
Please select walls and hosted openings so 6 element
[2019-02-01.zip](https://github.com/BHoM/Revit_Toolkit/files/2821191/2019-02-01.zip)

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub I am performing lots of test now PullRevit-Push XML and I spotted that `Storey ` are missing..  I logged this as separate issue but might be caused by some change here...

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

Storeys have nothing to the changes in this PR. Btw I do not remember I made any changes in regards to pull Storeys via Building. Are you sure it was pulling Storeys before?

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub 
my Environment `BuildingElements ` seems to be fixed and working but `Edges `does not work any more
image

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

There was no changes in Edges in this PR. It also works fine with me:
image

Could you please properly rebuild your code and make sure it is nothing related with your hardware?

Thanks in advance.

**Comment by michaldengusiak** [comment]
ok I isolated edges and I am happy with windows and skylights

**Pull request merged**
