### PR TITLE
Event suppression added to methods parsing properties of SpecTypeId and UnitTypeId

### LINKED ISSUE #1503: Redundant warnings when parsing properties of SpecTypeId and UnitTypeId
#### Description:

When all properties of `SpecTypeId` and `UnitTypeId` are parsed, irrelevant warnings are raised when the code hits e.g. this:
https://github.com/BHoM/Revit_Toolkit/blob/1e1a21dfa07455becff378aab2e5d44c42e1901b/Revit_Core_Engine/Objects/SpecTypeId.cs#L220-L230

Event suppression will be helpful.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1503

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by michal-pekacki — APPROVED** [review]
Changes make sense, happy to approve 👍

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
