### PR TITLE
Revit => BHoM freeform profile convert bugs fixed

### LINKED ISSUE #835: Revit_Toolkit: freeform profiles are pulled upside down
#### Description:

As in the title, nonsymmetrical freeform profiles get pulled upside down.

### LINKED ISSUE #836: Revit_Toolkit: Pull of freeform profiles crashing if !familySymbol.IsActive
#### Description:

As in the title, if !familySymbol.IsActive on convert of a freeform profile to BHoM, the code is crashing due to lack of geometry.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #835 
Closes #836

### Test files

- [#835](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue835%2DUpsideDownProfiles&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- [#836](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue836%2DInactiveProfileCrash&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - it is important not to create an element of a given type before pulling (it gets activated on the first use)
- macro test - _PullFramingLocation_ from [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPull&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302)

### Changelog

- Revit => BHoM freeform profile convert fixed to return the profile in correct orientation
- Revit => BHoM freeform profile convert fixed not to crash when pulling a non-active (loaded, but never used) family type

### Additional comments

The code has been cleaned up and simplified a bit in the process - it should not influence any existing behaviour, apart from the two fixes mentioned in the changelog.

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Code looks good; all tests work fine. LGTM

**Review by IsakNaslundBh — APPROVED** [review]
Test files fixes issues described. Approved

**Review by FraserGreenroyd — APPROVED** [review]
Code LGTM

**Pull request merged**
