### PR TITLE
Irrelevant error on pull of MEPCurves removed

### LINKED ISSUE #1264: Irrelevant error about querying panel locations for ducts not being supported
#### Description:

This got introduced by https://github.com/BHoM/Revit_Toolkit/pull/1238 and is caused by the fact that `MEPCurve` inherits from `HostObject`, which has been overlooked originally.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1264

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231265%2DIrrelevantDuctError&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Additional comments

@vietle-bh not sure how did this pass the Beta tests 🙈

### CODE REVIEW

**Comment by travispotterBH** [comment]
I'm all for suppressing as many errors/warning notes to the user if they are unnecessary,  as possible. They often are a scary to the user 😝

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Error gone when pulling pipes/ducts.

Pulling panels from a structural model works.

Not sure if anything else needs testing.

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
