### PR TITLE
Facade converts revamped

### LINKED ISSUE #1459: Facade panel converts are inconsistent
#### Description:

As in the title, over the iterations of development we managed to make the facade converts work, but they are quite inconsistent:
- there is a dedicated method to convert facade opening (`FacadeOpeningFromRevit`), but it is not used when querying the facade wall (it uses `FacadeCurtainPanels` instead)
- both methods have their dedicated ways of extracting geometry, construction, type etc.
- `refObjects` is not always leveraged
- opaque panels are returned as windows

In general another look would be welcome.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1459

### Test files

Standard facade pull test procedure + whatever you find relevant @enarhi. In general, the output should be the same or better, where better means:
- pull results being the same regardless of whether the element (panel/mullion) is pulled individually or as a member of curtain wall
- mullion type/profile not being `null`
- opening type being `CurtainWallSpandrel` in case of opaque curtain panels (please review carefully `BH.Revit.Engine.Core.Query.IsTransparent` methods)

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM, tested with test revit model and others pullng walls, windows, curtainwalls, and curtain systems and all pulled as expected including properties, geometry, etc.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check installer

**Review by enarhi — APPROVED** [review]
LGTM, new descriptions are appropriate per their methods.

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
