### PR TITLE
Irrelevant unit type warnings suppressed

### LINKED ISSUE #1325: Irrelevant warnings generated by UnitTypeByPropertyName query
#### Description:
In Revit <2021, on first call to `BH.Revit.Engine.Core.Query.UnitTypeByPropertyName`, a series of warnings about nonexistent unit types is raised because of the call to `CollectUnitTypes` that parses all properties of `SpecTypeId`, even the ones that do not exist in a given version of Revit. Two solutions could work:
- warning suppression for the time of parsing the properties
- making sure only relevant properties are being parsed (would not to figure out how to do that)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1325

### CODE REVIEW

**Review by michal-pekacki — APPROVED** [review]
Tested via [Revit_Tools-#751](https://github.com/BuroHappoldEngineering/Revit_Tools/pull/751) and it works as it should 👍

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
