### PR TITLE
CopyParameters fixed to copy the properties independent of parameters

### LINKED ISSUE #1145: CopyParameters is returning before properties are copied when RevitParametersToPush is missing
#### Description:

The following lines:
https://github.com/BHoM/Revit_Toolkit/blob/a71d99fa93ab5fbad0c01ac14885e090c186ab91/Revit_Core_Engine/Modify/CopyParameters.cs#L99-L101

Should be moved to line ~130 to make sure the properties get copied before the method returns due to the missing fragment.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1145

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231155%2DCopyParametersFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Additional comments

This is a bit of an edge case, but can be a pain when parameter mapping is used (see the test script).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by michal-pekacki — APPROVED** [review]
Tested and LGTM! 👍

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
