### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Updates Assembly Version to 4.3

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a CI/CD perspective.

**Review by pawelbaran — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Pull request merged**
