### PR TITLE
'Edited by' added to the default blacklist in diffing

### LINKED ISSUE #1430: Diffing: should 'Edited by' parameter be ignored by default?
#### Description:
While doing various diffing exercises, I noticed we keep on ruling out `Edited by` parameter - maybe we should simply add it to the ignored set by default? Thoughts against?

@alelom FYI the parameter informs about the last user that 'touched' a Revit element. So as long as it may be an important piece of information in many contexts, we usually do not care about it in diffing.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1430

### Test files

Standard diffing test procedure

### Additional comments

...I thought I will PR that tweak as I already had it ready on my local - happy to put the PR down if we end up disagreeing with the idea 😉

### CODE REVIEW

**Review by vietle-bh — APPROVED** [review]
I support this change 👍 
Let's see if @alelom feels the same 😄

**Review by alelom — APPROVED** [review]
Makes total sense to me! Approving on the base of code changes, not tested.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Reapproving based on previous reviews from @vietle-bh and @alelom as only change has been to copyright compliance since.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
