### PR TITLE
Align to Graphics_oM `Vertex` to `RenderPoint` refactoring

### LINKED ISSUE #1074: Align to Graphics_oM Vertex to RenderPoint refactoring
#### Broken rules:

See https://github.com/BHoM/BHoM/issues/1273

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2606
   
### Issues addressed by this PR

Closes #1074

### CODE REVIEW

**Review by enarhi — DISMISSED** [review]
LGTM, tested with pulling objects with RenderMesh enabled and behaved as expected with it coming through.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@alelom document compliance check is failing (and possibly null handling too). I am okay with dispensation, but this is something you need to agree upon with the CI team - getting coordinated may consume more time than simply adding the missing descriptions and checks, so up to you 😉

**Comment by pawelbaran** [comment]
The code changes as such LGTM, just in case.

**Comment by alelom** [comment]
@BHoMBot check required

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by alelom** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
I'd go for dispensation for null-handling @pawelbaran

**Comment by FraserGreenroyd** [comment]
@alelom see [this review] - the `null-handling` error is coming from your PR series and is being caught by the failure on the engine based on what I can see. This should be resolved and then `null-handling` should pass on both happily. Owing to the failure being the introduction of a new method, I am not currently supportive of a dispensation on this PR, but am happy to discuss timeframes in the morning if there is a concern over re-review of the engine, etc.

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
