### PR TITLE
IObject implemented to PullGeometryConfig and PullRepresentationConfig

### LINKED ISSUE #967: PullGeometryConfig and PullRepresentationConfig do not implement IObject interface
#### Description:
As in the title, urgent because the Create methods do not appear in the UI.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #967

### Test files

Run Grasshopper and try creating one of the subject objects - on `master` that is impossible, on this branch should work.

### Changelog

- `IObject` implemented to `PullGeometryConfig` and `PullRepresentationConfig`

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Looks and works good to me!

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Pull request merged**
