### PR TITLE
Query.OpeningSurfaces_Curtain to use Create.PlanarSurface to generate output

### LINKED ISSUE #1140: Query.OpeningSurfaces_Curtain is using constructor to create PlanarSurface instead of Create method
#### Description:

As in the title, this results in creation of invalid surfaces (e.g. with `ExternalOutlines == null`). Causing issues further downstream.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1140

### Test files

Try pulling walls using _FromLink_PullWallFloorRoofLocation.gh_ and _FromLink_PullPanelLocation.rvt_ from [this SharePoint folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Additional comments

@FraserGreenroyd this is a oneliner that should be 100% safe - I am not desperate to see this merged before the Beta release, so I leave the decision about hitting the green button to you 👍

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by enarhi — DISMISSED** [review]
LGTM, @FraserGreenroyd can we get this one merged please?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Reapproving following @enarhi review, owing to changes being a rebase to include a versioning fix in PR #1143

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
