### PR TITLE
Pull from links partially enabled

### LINKED ISSUE #396: Implement pulling elements from links
#### Description:
Would be great to be able to pull elements from links same as we do from active documents.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #396

### Test files

- [issue-specific test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23396%2DPullFromLinks&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- [standard test files for requests extended to links](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests%2FLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

**IMPORTANT:** Please see the additional comments for more information.

### Changelog

- `LinkRequest` object introduced
- handling of the above object implemented, enabling pulling from links

### Additional comments

First of all, apologies for the size of this PR - it has already been limited to the bare minimum, focusing on the framework-level changes. Large parts of code will require gradual refactoring in order to make pull from links fully functional. **The following functionality is not implemented yet:**
- pull of physical `ISurfaces` (walls, floors, roofs etc.) and `IOpenings` (windows, doors etc.)
- pull of ceiling patterns (pull of ceilings does not work on two levels: this and above 😃)
- pull from links that are transformed with regard to the host document does not handle the transformation - temporary warnings added where necessary
- link information does not get saved to `RevitIdentifiers`

**Another few limitations are permanent due to limitations of Revit:**
- selection, active view and active workset requests do not work in combination with `LinkRequest` - relevant messages added
- `Remove` does not work with `LinkRequest` - relevant message added

**A few follow-up issues to be raised once this PR gets merged:**
- add link information to `RevitIdentifiers`
- introduce pull of `ISurfaces`, `IOpenings` from links (if possible - Revit API is a monster here)
- introduce pull of ceiling patterns from links
- enable transform of elements pulled from links

Finally, @LMarkowski looks like there will be no conflict between this PR and #956 since this one is dealing mainly with `FromRevit`, while the latter with `ToRevit`.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by LMarkowski — CHANGES_REQUESTED** [review]
I've checked the code and despite the size of the PR, everything looks comprehensible and (more importantly 😉) correct.

However I had one issue funcionality-wise:
image
Pulling by link name only doesn't seem to work.
It is fine however when provided with a full path (with or without `.rvt`)

**Comment by pawelbaran** [comment]
Thanks @LMarkowski for the review, looks like the format, in which the values are stored under `Document.Title` property has changed between 2018 and 2020 (why would you keep consistent when it comes to such minor characteristics as document title? 🤣). Luckily there is a bypass available for that, should work fine after the fix.

**Review by LMarkowski — CHANGES_REQUESTED** [review]
On Rvt 2020 everything works like a charm, but now on Rvt 2018 on the other hand... 😅 
image
It works good with a full path so it's still must be something with how rvt stores links properties.

**Comment by pawelbaran** [comment]
Weird stuff going on here @LMarkowski - after encountering similar issues on my machine, I have just tried on a fresh Alpha installer, works like charm on 2018, 2020 and 2021!

In my case the code worked fine, but the errors were not passed to the UI (even though Revit_TK code was recording them correctly!). I am pretty sure that was the fallout from the all-breaking changes I have introduced to the Reflection_Engine earlier today.

Could you please try again, starting off the fresh Alpha? It is a bit smelly that we both had issues at the same time, but I cannot think of any code improvement above my last commit, so hopefully it was just a bad luck of us both being on wrong branches in other repos.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Review by LMarkowski — COMMENTED** [review]
> Weird stuff going on here

..and there is more. I'm on a today's daily alpha. Everything is being pulled (or not) correctly on both RVT 18 and 20, but no events are being exposed..
image

**Comment by pawelbaran** [comment]
> > Weird stuff going on here
> 
> ..and there is more. I'm on a today's daily alpha. Everything is being pulled (or not) correctly on both RVT 18 and 20, but no events are being exposed..

Apparently the events do not get passed from Revit already on master, so it seems to be out of the scope of this PR. I will dig deeper to find out where does the recording problem lie.

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@LMarkowski FYI, I have raised https://github.com/BHoM/BHoM_UI/issues/374 that I believe is the source of our current confusion here.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by LMarkowski — APPROVED** [review]
Approving as missing events are a global issue out of scope of this PR.

**Pull request merged**
