### PR TITLE
Querying link documents for ElementIds made more robust and errors made more informative

### LINKED ISSUE #999: Checks of link request combinations require revisiting and possible refactoring
#### Description:

As in the title, the checks done on link request combinations bear a few issues:
- they are done in `SplitRequestTreeByLinks`, which can easily be bypassed in the code, leading to crashes directly in ElementId filtering methods
- the messages contain errors coming from reckless copy-paste 🙈

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #999

### Test files

_Link_StandardRequests_ on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests%2FLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - no need to go through the whole test file, only orange groups should be relevant.

### Changelog

- Querying link documents for ElementIds made more robust and errors made more informative

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Code LGTM and works as expected. Approving.

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Pull request merged**
