### PR TITLE
Revit_Core_Engine: Create View3D no longer converts value to feet

### LINKED ISSUE #1024: Revit_Core_Engine: Create View3D is converting a value to feet
#### Description:
There is a line in the code that converts `horizontalFieldOfView` to feet. A bit of a short sight of my part, this side of the code should never convert units, just spit out the values regardless of it.

#### Steps to reproduce:
N/A

#### Expected behaviour:
To not convert double value to feet.

#### Test file(s):
N/A

### PR DESCRIPTION
**Pull request by tiagogrossi**
### Issues addressed by this PR
Closes #1024 

The code no longer converts `horizontalFieldOfView` to feet.

### Test files
N/A

### Changelog
Modified `BH.Revit.Engine.Core.Create.View3D`

### CODE REVIEW

**Review by pawelbaran — DISMISSED** [review]
Following the discussion LGTM @tiagogrossi 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
> @tiagogrossi there seem to be some issues with compliance, could you please liaise with @FraserGreenroyd in order to resolve them (or get an exemption)? Thanks!

Documentation compliance needs fixing for the errors, they can't be exempted.

Code compliance is easily fixed by renaming the file to have a capital `D` at the end of it which I'd rather see done than exempting it.

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check copyright-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check dataset-compliance

**Review by pawelbaran — APPROVED** [review]
LGTM, neat cleanup

**Pull request merged**
