### PR TITLE
Mesh and geometry representations of elements cleaned up

### LINKED ISSUE #689: Revit_Toolkit: Pass material render information to RenderMesh
#### Description:
Atm only geometry of the mesh is passed to `RenderMesh` - would be nice to allow converting material information too.

@alelom @al-fisher FYI

### LINKED ISSUE #690: Revit_Toolkit: Clean up element geometry queries
#### Description:
Following https://github.com/BHoM/Revit_Toolkit/pull/686, a few improvements could be done to the elementy geometry queries:
- remove boilerplate shared by `Curves`, `Surfaces` and `Meshes` methods
- support curves better (meshes with nodes of valence 1 and 2?
- #689

### LINKED ISSUE #693: Revit_Toolkit: Remove RenderMesh class from Adapter_Revit_UI
#### Description:

Created by coincidence due to ctrl+. missclick 🐒

### LINKED ISSUE #694: Revit_Toolkit: Pulling meshes breaks for some voids
#### Description:

Some voids/door openings seem to break the code when pulling mesh representations.

#### Test file(s):

On [SharePoint]().

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/1753

   
### Issues addressed by this PR

Closes #689
Closes #690
Closes #693
Closes #694

### Test files

General test on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue685%2DPullRepresentations)
#694 on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue694%2DPullMeshBug)

### Changelog

- `BH.UI.Revit.Engine.Query.GeometryPrimitives` method has been implemented to retrieve all geometry primitives from an element
- `Curves`, `Faces` and `Surfaces` query methods have been refactored to return types from `Autodesk.Revit.DB` namespace instead of `BH.oM.Geometry` - converts happen further down the line
- `BH.UI.Revit.Engine.Query.MeshedGeometry` and `BH.UI.Revit.Engine.Query.RenderMeshes` methods have been implemented to enable querying elements with a single call
- `FromRevit` convert between `Autodesk.Revit.DB.Color` and `System.Drawing.Color` has been implemented
- `BH.UI.Revit.Engine.Query.BoundingBox(Element)` method has been removed as unused

### Additional comments

Faces of meshes based on curves come out with `B == C`, which may cause issues, e.g. Grasshopper sees it as _Invalid Mesh_ etc. However, I believe this is still more correct than returning `Polylines` mixed with `Meshes`.

Besides that does not look bad:
image

### CODE REVIEW

**Comment by pawelbaran** [comment]
Alpha added to colour:

image

**Comment by FraserGreenroyd** [comment]
LGTM

**Pull request merged**
