### PR TITLE
FilterByScopeBox implemented

### LINKED ISSUE #964: Implement FilterByScopeBox
#### Description:

...to allow filtering elements by given scope box. Optional parameter: contains vs intersects.

**Warning:** Possible slow request, slower than parameter requests?

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #964

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23978%2DFilterByScopeBox&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - testing on an Alpha from 18th Feb or older is recommended to see the errors and warnings in GH.

### Changelog

- `FilterByScopeBox` 
- `HostDocument` and `LinkTransform` methods separated from the code base

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by michaldengusiak** [comment]
@pawelbaran this sounds interesting, would be possible to share an example when completed...?

**Comment by pawelbaran** [comment]
Hi @michaldengusiak! Still following us? 😉 I will try to remember to add an example, but just in case, it should be really easy to do by yourself, simply try the `FilterByScopeBox` request, it should be self-explanatory.

**Review by LMarkowski — APPROVED** [review]
Code lgtm. In test files everything works as supposed.

Looking forward for implementation of transforms 😄 
Also putting a note here about what we talked on Teams which is an idea of adding as well filtering by `BH.oM.Geometry.Cuboid` besides the ScopeBox.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Pull request merged**
