### PR TITLE
Deprecated 3.3 code removed

### LINKED ISSUE #1006: Remove deprecated code older than 4.0
#### Description:

As in the title, quarterly cleanup.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1006

### Test files

Not sure how to phrase that but... not needed 👼

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
> ### Test files
> Not sure how to phrase that but... not needed 👼

https://media1.tenor.com/images/6194b11ecf642fc9c0ac0ccb8ebce0a0/tenor.gif?itemid=10398912

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Code removed was deprecated in 3.3, versioning is happy, so I'm happy.

**Pull request merged**
