### PR TITLE
ToRevit nurbs curve convert fixed to return an approximate polyline instead of a distorted hermite spline

### LINKED ISSUE #866: Revit_Toolkit: BHoM => Revit nurbs curve convert distorts the curve in some cases
#### Description:

As in the title, currently in some cases the output of BHoM => Revit convert causes distortion of the curve due to conversion to hermite spline:
https://github.com/BHoM/Revit_Toolkit/blob/beaa05faded8c581d890d97ab269a0d0d54a38f8/Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs#L85-L103

That should be improved by approximating the nurbs curve with a more primitive entity, which should be possible once https://github.com/BHoM/BHoM_Engine/issues/2016 gets resolved.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2231

   
### Issues addressed by this PR

Closes #866

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23866%2DNurbsConvertBug%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit) - to be ran on an empty Revit model (please make sure the construction name in GH script is aligned with an existing floor type name in Revit).

### Changelog

- `ToRevit` nurbs curve convert fixed to return an approximate polyline instead of a distorted hermite spline

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
LGTM in line with Engine PR

**Pull request merged**
