### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Update Assembly Version to 5.0.0.0
Update Assembly File Version to 5.0.0.0

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
LGTM, thanks @FraserGreenroyd 👍

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3734750695

**Pull request merged**
