### PR TITLE
Warnings about nonplanar faces added when querying panel surfaces

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes part of #1287

### Test files

Run the standard panel pull procedure and check the culprit highlighted in https://github.com/BHoM/Revit_Toolkit/issues/1287.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check versioning
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Warnings are sufficient and make sense from code review.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
