### PR TITLE
Added convert FromRevit for CableTray object

### LINKED ISSUE #859: Revit_Toolkit: Add Revit=> BHoM convert for CableTray objects
#### Description:
Following the obj definition of `CableTray` in `MEP_oM` and `MEP_Engine` it is now necessary to create the converts `FromRevit`.
In Revit fittings are not represented as linear objects, only as points for their location, meaning that a pure extraction of geometry from the Revit API will cause gaps in a network of cable trays, like this example:
diagram1
One possible attempt to go around this as exemplified in red in the picture, is to bypass the fitting by querying to what it is connected to, and sort of "snap" cable trays together.

An awkward scenario is also found where cable trays are connected to each other WITHOUT fittings, by mistake possibly or by design. In that scenario exemplified in the following picture the original 1 Cable Tray must be split into many, effectively increasing the number of items: 
diagram2

### PR DESCRIPTION
**Pull request by tiagogrossi**
### Issues addressed by this PR
Closes #859

Ignores BHoM/MEP_oM#1034

Initial convert FromRevit created for `CableTray` objects, that bypasses fittings to query its connectors to allow its line creation without gaps at fittings. This behavior has been replicated for `Duct` and `Pipe`.
An important observation is that pulling these objects may not result into a single element anymore, but a list of elements(e.g. if a cable tray has cable trays connected to it without fittings, or when there is a chain of fittings connected)

### Test files
Test files [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue859-AddedConvertFromRevitForCableTrays?csf=1&web=1&e=Z4MkTp).

### Changelog
Added `Revit_Core_Engine.Convert.Environment.FromRevit.CableTray`
Added `Revit_Core_Engine.Query.CableTraySectionProfile`
Added `Revit_Core_Engine.Query.CableTraySectionProperty`
Modified `Revit_Core_Engine.Convert.Environment.FromRevit.Duct`
Modified `Revit_Core_Engine.Convert.Environment.FromRevit.Pipe`
Modified `Revit_Core_Engine.Convert.FromRevit`
Modified `Revit_Core_Engine.Query.OrientationAngle`
Modified `Revit_Core_Engine.Query.Profile`
Modified `Revit_Core_Engine.Query.LocationCurve`

### Additional comments
Due to recent changes in MEP namespaces `CableTray` will be pulled without a proper line geometry, but it's being pulled nevertheless. This will be addressed in the core BHoM repo at the object level.

### CODE REVIEW

**Comment by tiagogrossi** [comment]
@pawelbaran as mentioned I've closed #880 because of branch conflicts. You had approved the old one but please feel free to look again into it. @FraserGreenroyd  you had requested changes to #880 that I believe were addressed, any thoughts?

**Review by pawelbaran — APPROVED** [review]
Still LGTM code wise, would be great if the 2nd reviewer could test the functionality.

**Review by FraserGreenroyd — APPROVED** [review]
From what I can see my changes have been addressed, happy for this to be merged

**Pull request merged**
