### PR TITLE
Revit_Core_Engine: Query descriptions added plus code cleaned up

### LINKED ISSUE #596: Add descriptions to Revit_Core_Engine
#### What is missing/incorrect?

As in the title, there is no descriptions in Engine_Revit_UI - to be added.

### LINKED ISSUE #1144: Rename IsInside to IsContaining
#### Description:

...to follow the general BHoM convention. Remember about swapping the inputs!

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #596
Closes #1144

### Test files

Most of the checks should be done by @BHoMBot. The only human test I would recommend is _OpeningConverts_ from [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231127%2DOpeningConverts%2FOpenings&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Changelog

- descriptions added to Revit_Core_Engine/Query
- `FacadePanelAsOpening` and `ArbitraryPlane` methods made private as keeping them public could result in misuse
- `CurtainWallCurves` method removed as unused legacy (confirmed with @enarhi)
- `Level` method removed as unused legacy
- `EnergyAnalysisElementName` method removed as a duplicate of `FamilyTypeFullName`
- `IsInside` method renamed to `IsContaining` to follow the BHoM naming convention

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by michal-pekacki — APPROVED** [review]
LGTM! 👍

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
