### PR TITLE
Added owner to Checkout Status methods

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #

Added owner `out` parameter to `Checkout Status` methods.

### CODE REVIEW

**Comment by travispotterBH** [comment]
Also, if we are going to use the out parameter here for the owner, if the owner is empty I believe we should be doing this check here and not sending out null, rather sending out "unknown" or something similar, lest we end up with something like this: 
image

**Comment by michal-pekacki** [comment]
@travispotterBH, I fully agree and changed the methods according to your suggestions 👍

**Review by travispotterBH — DISMISSED** [review]
Thanks for picking up my comments. Happy to approve.

**Comment by michal-pekacki** [comment]
@BHoMBot check compliance

**Comment by travispotterBH** [comment]
@BHoMBot  check required

**Comment by travispotterBH** [comment]
@BHoMBot  check beta-required

**Comment by michal-pekacki** [comment]
@BHoMBot check compliance

**Review by vietle-bh — APPROVED** [review]
Approving after code checking and testing it through the dependent PR.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
