### PR TITLE
BoundingBoxXYZ.FromRevit() added and closest element query tweaked to optionally include nested curtain elements

### LINKED ISSUE #1277: Add FromRevit convert for bounding boxes
#### Description:

As in the title

### LINKED ISSUE #1278: BH.Revit.Engine.Core.Query.ClosestElement: Enable searching through nested curtain elements

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1277
Closes #1278

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Review by michal-pekacki — CHANGES_REQUESTED** [review]
Converting to `BH.oM.Geometry.BoundingBox` will definatelly be useful in geometric methods and I'm happy with this part 👍 

One comment to the `ClosestElement` method:

https://github.com/BHoM/Revit_Toolkit/blob/6849abec26ffb76c9303509dc98f852367c43bb7/Revit_Core_Engine/Query/ClosestElement.cs#L70-L77

Shouldn't we get the location of non-point elements? We can do it in the same way as in line 129:
https://github.com/BHoM/Revit_Toolkit/blob/6849abec26ffb76c9303509dc98f852367c43bb7/Revit_Core_Engine/Query/ClosestElement.cs#L129

**Comment by pawelbaran** [comment]
Fair point @michal-pekacki, I have rewritten the method to actually cover all types of locations - should be ready to re-review now.

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check ready-to-merge

**Pull request merged**
