### PR TITLE
Misaligned namespaces fixed

### LINKED ISSUE #1085: Misaligned namespaces
#### Broken rules:

Three namespaces have been identified as breaking the rules:
- Revit_oM: `BH.oM.Revit.Parameters` should be `BH.oM.Adapters.Revit.Parameters`
- Revit_Engine: `BH.Engine.Revit` should be `BH.Engine.Adapters.Revit`
- Revit_Core_Engine: `BH.Engine.Adapters.Revit` should be `BH.Revit.Engine.Core`

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1085

### Test files

Sanity check .gh file uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231086%2DMisalignedNamespaces&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), but I believe a versioning check should be enough of a verification.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd I have requested dispensation for the documentation compliance check - the requested descriptions have been added in a parallel PR (https://github.com/BHoM/Revit_Toolkit/pull/1081), so I believe it is fine to get this one merged as is 👍

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check installer
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3613352085

Per @pawelbaran comment, I have reviewed the files changed in #1081 and the annotations recorded as errors in this PR and am satisfied that #1081 will resolve them, so am dispensating the check on this PR to avoid needing to duplicate work or cause clashes.

**Review by FraserGreenroyd — APPROVED** [review]
All LGTM on a code review based on the issue raised and CI checks for versioning.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
