### PR TITLE
BHoM <-> Revit type queries refactored and BHoM type-based pull fixed

### LINKED ISSUE #443: Revit_Toolkit: Refactor BHoM <-> Revit type queries into data structures
#### Description:
At the moment there is a few methods that define the relationship between BHoM and Revit types and categories:
- [ ] `BH.UI.Revit.Engine.Query.BHoMTypes`
- [ ] `BH.UI.Revit.Engine.Query.BuiltInCategories`
- [ ] `BH.UI.Revit.Engine.Query.BuiltInCategory`
- [ ] `BH.UI.Revit.Engine.Query.FramingType`
- [x] `BH.UI.Revit.Engine.Query.RevitType`
- [ ] `BH.UI.Revit.Engine.Query.RevitTypes`

We need to structure and document these as tables and reflect in code in a form of appropriate data structures.

### LINKED ISSUE #560: ModelInstance and DraftingInstance type-based pull returns too many items
#### Description:

Looks like all objects of type `FamilyInstance` are pulled instead of `ModelInstances` and `DraftingInstances`

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue560%2DInstancePullBug).

### LINKED ISSUE #580: Revit_Toolkit: ElementIdsByBHoMType null return bug
#### Description:
When hitting line 78, `ElementIdsByBHoMType` returns null that crashes the code.
https://github.com/BHoM/Revit_Toolkit/blob/2fd99a3179cda7e86b43a5120cd9684caca19c26/Engine_Revit_UI/Query/ElementIds/ElementIdsByBHoMType.cs#L74-L79

This should return a new list of `ElementIds` instead.

To be done together with #443.

### LINKED ISSUE #581: Revit_Toolkit: BH.UI.Revit.Engine.Query.RevitTypes returns null for BH.oM.Physical.Materials.Material
#### Description:
As in the title: due to this bug it is impossible to pull materials without pulling the elements.

To be fixed together with #443.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #443
Closes #560
Closes #580
Closes #581

### Test files

[Issue specific test](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue443%2DBHoMRevitTypes)
[Macro tests](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull)

### Changelog

- mechanics of `ElementIdsByBHoMType` method have been changed to work on Reflection, thanks to which counterintuitive and virtually unmanageable `RevitTypes` if/else method is not needed any more - the whole framework should become more scaleable (any convert method should be picked up as long as its name starts from _ToBHoM_, is callable by `IToBHoM` dispatcher method and its first argument inherits from `Autodesk.Revit.DB.Element`
- `BuiltInCategories` method has been refactored from a massive if/else method into a `static readonly` dictionary with a method that manages it - its scope has been limited to objects of type `FamilyInstance` only, therefore the dictionary will not need to be revisited too often
- `FramingType` query has been removed altogether
- massive if/else `BHoMTypes` methods have been refactored (first has been embedded directly in `ToBHoMProfile`, which previously was calling it generating boilerplate and overhead, second has been turned into a `static readonly` dictionary with a method to manage it)
- support methods were added and existing ToBHoM methods updated to unlock the above
- ToBHoM conversion of framing elements and physical panels has been split across multiple files and cleaned up
- conversion methods for framing profiles have been cleaned up

### Additional comments
**This PR is meant not change anything to worse for the end user.** If something changed, it should be for better, i. e. filtering should be more precise and a few bugs should be gone. Therefore, regardless gargantuan volume of this PR I believe it should not be extremely hard to test it functionality wise.

### CODE REVIEW

**Comment by pawelbaran** [comment]
I would be veeery thankful for proactive review as the end of last dev week is coming close.
@kThorsager @MajaLindroth could you please review the functionality (project scripts are welcome)?
@IsakNaslundBh could you have a look at the changes that touch structural/physical elements?
@FraserGreenroyd it would be great if you could look into reflection aspects - I am far from good in that field so high chance some thing could be done better.

Thank you all!

**Comment by kThorsager** [comment]
An initial comment is that I'm now getting my foundation slabs when pulling panels, which I did not receive beforehand. Not necessarily bad, since they are getting through as Panels, but strange in a refactor PR.

**Comment by pawelbaran** [comment]
@kThorsager I guess this refers to the section where I mentioned that:

> If something changed, it should be for better

... unfortunately, the next words were:

> (...) not different (...)

🙈 

I slightly changed the last part of the description to reflect the changes better. The difference comes from the complete refactor of filtering, as described on the top of this thread: before only types hard-coded to be converted to Panels were being pulled (foundation slabs must have been missed by me when hardcoding the if/else method), now any Revit element that can be converted to a Panel (has a method to do it) will be pulled.

Is that something you would consider an issue to your current project work? I think this change is a change for better plus it needs to happen at some point to improve scalability, but could consider some fallbacks/workarounds if you feel like this is likely to become a problem.

**Comment by kThorsager** [comment]
Won' affect my current project at all as we're not working on the lower levels, (and I don't think I would see it as a problem then either). Mostly flagged as unexpected features sometimes means a similar collection of unexpected bugs. But sounds like it's not that unexpected.

**Comment by pawelbaran** [comment]
Yeah this falls into the expected scope of unexpected changes. I put on my end-user-targeted changelog that I am planning to communicate on Yammer in parallel to the BHoM change log.

**Comment by MajaLindroth** [comment]
I find that when pulling only panels almost all of them get duplicated. When pushing to XML this means that the extra panels lies as shading elements on top of the original panel. 

image

**Comment by pawelbaran** [comment]
> The Corinthian column was not pulled as a bar, returning either a `null` object or a error message. suspect that this might be intended.

Indeed, that is happening on purpose (Corynthian column is nonbearing, it only carries the burden of history). Although can be worth logging some more informative warning - I am happy to raise an issue and tackle it in the next Milestone.

> Physical & Enviormental walls top offset is not accounted for:
> image
> It is however accounted for when pulling as structural wall.

This refers to the way in which the converts deal with attached walls - it has not been changes in this PR, so it is outside of its scope. I am looking towards revisiting all methods related to walls/slabs/framing in the next Milestone, so will keep it as a test case for then.

> Both the group Material & Material fragments returns Materials, and tried to pull `Material`, changed it to `IMaterialProperties` but the result was the same. The group further down which pulls `IMaterialFragment` (which is a subset of `IMaterialProperties`) works however, dispite claims about being disallowed
> image
 
Looks like it was my bad, I mistook the groups and set up `Material` test twice and moved `IMaterialFragment` test to disallowed. I have corrected the test file, the three groups should pull:
- `Material`
- `IMaterialFragment`
- `ModelInstance` (disallowed)

Apologies for that one - could you please double check now? On my build I get correct results for both physical `Material` as well as `IMaterialFragment`:

image


> Are these bugs to be concerned about @pawelbaran ?

All bugs should make us concerned @kThorsager  😜 But I think (hope) I managed to defend my stance against the ones you have raised in the comment - one of them was caused by me overwriting my own test script, the other two are to be fixed in the next Milestone (I have already put them in my roadmap). I am OK with these for now if you are OK too.

**Comment by pawelbaran** [comment]
@MajaLindroth nice catch! I think I have found the source of that issue, it is related to the boilerplate in BEnv Panel convert methods. I pushed a fix, changed accessibility of two methods from `public` to `internal`, which in practice should lead to the same behaviour as before this PR.

To be followed up in #541.

**Comment by kThorsager** [comment]
Nice @pawelbaran ,
My last concern is that pulling `IMaterialProperties` returns a `Material` which is wrong, `Material` contains a list of `IMaterialProperties` but is not one.
image

I'm happy if this is out of scope.

**Comment by pawelbaran** [comment]
> Nice @pawelbaran ,
> My last concern is that pulling `IMaterialProperties` returns a `Material` which is wrong, `Material` contains a list of `IMaterialProperties` but is not one.
> image
> 
> I'm happy if this is out of scope.

This happens due the fact that currently Revit Material has 4 ToBHoM methods:
- `BH.oM.Environment.MaterialFragments.IEnvironmentMaterial`
- `BH.oM.Structure.MaterialFragments.IMaterialFragment`
- `BH.oM.Physical.Materials.Material`
- `BH.oM.Physical.Materials.IMaterialProperties`

Where only 3 first can actually be reached on convert. Since `IMaterialProperties` belongs to `Physical` namespace, it got converted to `Material`. To avoid confusion, I disallowed pulling `IMaterialProperties`, leaving the other three options available.

**Comment by pawelbaran** [comment]
Facing the number of spotted errors, I have added a few more test cases in the issue-specific test file @kThorsager as well as BEnv macro pull test file (pull of spaces, seems to work same as on master branch) @MajaLindroth.

I hope the above were the last errors to be found, though any further tests will be very welcome.

**Comment by MajaLindroth** [comment]
Duplication problem looks to be solved now. But I do find that when pulling panels I also get a couple of "modelInstance". This did not occur before so I'm flagging it. 

image

**Comment by pawelbaran** [comment]
@MajaLindroth it should be fixed now

**Pull request merged**
