### PR TITLE
Category, family and element type queries refactored

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Prep work for #582 - the actual problem stated in the issue to be resolved in next PRs.

### Test files

- [problem-specific test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue582%2DElementTypeQuery&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - proves that types are matched nicely for core types both on create and update + `FamilyLibrary` works to the extent provided on `master` (this will be further refined right after this PR, so missing functionality is acceptable)
- [push of drafting instances](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue505%2DSupportForFilledRegionsAndLineBasedDetailItems&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - beta 4.0 version of the file available in the folder
- [push of sheets/views and instances](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue878%2DRemoveCustomData&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - _Representations.gh_ irrelevant
- [standard push tests](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPush&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302) - rather an extra, only type matching should be affected (all should still work)

### Changelog

- `BuiltInCategory`, `BuiltInCategories` and `ElementType` queries simplified and unified as much as possible
- all converts returning objects that inherit from `ElementType` renamed to `ToRevitElementType`

### Additional comments

Comparing the code might be rather tricky - at some points even I gave up on trying to understand what is going on and simply removed big chunks of most convoluted codebase to rewrite it from scratch. Therefore, I suggest looking at the changes as greenfield wherever one can see there is a massive intervention.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
The input parameter being lowercase is the only bit that needs fixing, the rest will be resolved with the 4.1 decision to return `void` on Modify methods so am happy with that being left.

**Comment by pawelbaran** [comment]
> The input parameter being lowercase is the only bit that needs fixing, the rest will be resolved with the 4.1 decision to return `void` on Modify methods so am happy with that being left.

done @FraserGreenroyd 👮

**Review by michaelhoehn — APPROVED** [review]
Approving from a functionality standpoint. I've tested the referenced files and all functions nicely from my point of view. 👍 

I've also taken a brief look through the code and see no glaring issues, but would certainly rely on others to comment on anything specific.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
I'm now happy, only remaining code compliance is the modify stuff which is already noted as being ok.

**Review by LMarkowski — APPROVED** [review]
Funcionality-wise everything works as expected.
Didn't find anything odd in the code.
LGTM 👍

**Pull request merged**
