### PR TITLE
Prefiltering by workset optimised

### LINKED ISSUE #1188: Prefiltering by workset takes very long in case of large models
#### Description:

As identified by @IsakNaslundBh and debugged by us two, initial filtering of elements by workset in `Read` method may take up to 20s, which is far from ideal. Optimisation is needed in this field.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1188

### Test files

Any monstrous file with worksets should suffice - @IsakNaslundBh should have one at hand 👍

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Review by IsakNaslundBh — COMMENTED** [review]
This drastically improves the performance on pulling from a model with multiple closed worksets. Example model goes from 20 seconds to 0.5s when pulling a set of grids/levels.

Code generally looks fine as well, besides required compliance fixes, but good with a quick chat to check tast my testing is sufficient!

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check installer
@BHoMBot check versioning

**Review by IsakNaslundBh — APPROVED** [review]
Approving based on previous testing!

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6083793164

**Pull request merged**
