### PR TITLE
Family library Create method tweaked to scrape type names from .txt file

### LINKED ISSUE #1513: Family library scrapes types only from the .rfa file, not .txt
#### Description:

As in the title, when `FamilyLibrary` object is created, it scrapes a chosen folder finding all families and types. Currently the feature is quite limited because only .rfa files are scraped for types, not .txt.

Thanks for flagging it @ssiimmoonnee 👍

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1513

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231514%2DScrapeTxtInFamilyLibrary) - download the family together with .txt, then update the script to point at the folder containing them, check if all family types are scraped.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by ssiimmoonnee** [comment]
Tested in Revit 2022. It works for me.

**Review by ssiimmoonnee — APPROVED** [review]
Tested in Revit 2022. Works fine for me!

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
