### PR TITLE
Push of Foundation Slabs enabled

### LINKED ISSUE #1071: Foundation Slabs can be pulled as Physical Floor but cannot be pushed
#### Description:

As in the title, spotted by @ssiimmoonnee. This is because of the missing category in the `ToRevit` convert:
https://github.com/BHoM/Revit_Toolkit/blob/2957107fbedf16fbb4a25830ea7703da82aea628/Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs#L55-L57

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

Not directly, but easier to review with https://github.com/BHoM/BHoM_Engine/pull/2608

   
### Issues addressed by this PR

Closes #1071

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231073%2DCreateFoundationSlabFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by ssiimmoonnee — APPROVED** [review]
Tested in Revit 2021, it works. Thanks, Pawel.

**Review by ssiimmoonnee — APPROVED** [review]
Thanks

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
