### PR TITLE
Calls to `new PlanarSurface(ICurve, null)` replaced with `BH.Engine.Geometry.Create.PlanarSurface`

### LINKED ISSUE #1345: Code calling new PlanarSurface(ICurve, null) to create a surface causes issues downstream
#### Description:
On a few occasions `PlanarSurface` gets created via call to `new PlanarSurface`, which is dangerous on a few levels:
- allows creation of invalid planar surface objects (nonplanar etc.)
- if `null` is passed to any of the two main properties, it causes issues downstream, see the test file

...instead, `BH.Engine.Geometry.Create.PlanarSurface` should be used.

#### Test file:
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231345%2DPlanarSurfaceConstructorIssues&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1345

### Test files

As in https://github.com/BHoM/Revit_Toolkit/issues/1345, also standard procedure for pull of panels needs to be re-tested.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by vietle-bh** [comment]
In the issue, the link to test files only links to the issue itself.

**Review by vietle-bh — COMMENTED** [review]
It worked on the test file you provide but raised some errors on the test scripts below:

[Test scripts](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Revit_Toolkit/%231345-PlanarSurfaceConstructorIssues/Test?csf=1&web=1&e=dMoRuh)

image

image

**Comment by pawelbaran** [comment]
Oke, it sounds like we again enjoy the differences between Revit and BHoM tolerances, the latter being more strict, therefore causing errors - thank you for spotting @vietle-bh 👍 I have restored the constructors instead of `Create` methods where applicable (e.g. on planar face converts - no need to re-do all planarity checks etc.), the only tweak now being passing `new List<ICurve>` instead of `null`, which should eliminate the original error reported in #1345.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Review by vietle-bh — APPROVED** [review]
All tests have passed

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
