### PR TITLE
Revit_Toolkit-Issue273-SpaceName

### LINKED ISSUE #273: Revit_Toolkit: Space Name
Environment Space should be 

`aName = string.Format("{0} {1}", BuiltInParameter.ROOM_NUMBER, BuiltInParameter.ROOM_NAME);`

### PR DESCRIPTION
**Pull request by ZiolkowskiJakub**
### Issues addressed by this PR
Space Name updated to match Environmental standards

Closes #273 

### Test files
[Sample Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue273-SpaceName?csf=1&e=2zL8kZ)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh says should be fine without structural review in BHoM call :smile:

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak, 

It is fixed now. Please test.

**Comment by michaldengusiak** [comment]
almost there
image

**Comment by ZiolkowskiJakub** [comment]
Sorry for that. Fixed now

**Pull request merged**
