### PR TITLE
Elements In Path - incorrect order bug fix

### LINKED ISSUE #1489: Elements in path - incorrect order
#### Description:

`Query.ElementInPath` could return results with incorrect order as it is based on `HashSet<int>`.

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #1489 

Replace `HashSet<int>` with `List<ElementId>` to keep correct elements order.

### CODE REVIEW

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
The code still works as expected, with the correct element order. Happy to approve

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by michal-pekacki** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
