### PR TITLE
Column style fixed on push of vertical columns + setting enum parameters re-enabled

### LINKED ISSUE #1254: Columns come out with type Slanted when they are vertical on Push
#### Description:

AS in the title: when pushing new vertical columns to Revit, they are created with type slanted, which makes little sense.

### LINKED ISSUE #1255: Setting parameters by enum values does not work
#### Description:

As in the title: when trying to set enum parameters on Push, the value does not get set to the element correctly. This is caused by the recent refactoring of `SetParameter` method, during which `parameter.Definition.ParameterType == ParameterType.Invalid` has been changed to `parameter.Definition.ParameterType() == null`. However, the latter does not return null for Revit 2021 and above, instead it returns `ForgeTypeId` with empty `TypeId` property.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1254
Closes #1255

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231257%2DPushVerticalColumn&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — APPROVED** [review]
Code looks great & works well.

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
