### PR TITLE
Move towards using ceiling tiles for ceilings

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1032
https://github.com/BHoM/BHoM_Engine/pull/2068

### CODE REVIEW

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Review by JohannaOlin1 — APPROVED** [review]
Tested and LGTM

**Review by pawelbaran — APPROVED** [review]
LGTM by the looks of code.

**Pull request merged**
