### PR TITLE
Revit_Core_Engine: View creation fails when modifying detail level

### LINKED ISSUE #1028: Views creation fails when changing property that view templates control
#### Description:
Some of the methods for view creation in `BH.Revit.Engine.Core.Create` have optional functionality to change the view's detail level, which fails when the view has a view template that locks that property.

#### Steps to reproduce:
N/A

#### Expected behaviour:
We must insert the appropriate checks in the code to avoid this attempt.

#### Test file(s):
N/A

### PR DESCRIPTION
**Pull request by tiagogrossi**
### Issues addressed by this PR

Closes #1028 

An `if/else` statement has been included to address the scenario where detail level cannot be set due to it being controlled by a view template.

### Test files
N/A

### Changelog
Modified `BH.Revit.Engine.Core.Create.View3D` with the if/else statement.
Modified `BH.Revit.Engine.Core.Create.ViewPlan` with the if/else statement.
Modified `BH.Revit.Engine.Core.Create.ViewSection` with the if/else statement.

### CODE REVIEW

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check dataset-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check copyright-compliance

**Review by pawelbaran — CHANGES_REQUESTED** [review]
It looks like you are adding literally the same code to 4 different methods. If that is the case, I would rather add a new method like `public static bool TrySetDetailLevel(this View view, ViewDetailLevel viewDetailLevel)` and put the code there to avoid boilerplate.

Besides that, the fix itself looks good 👍

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check core

**Comment by tiagogrossi** [comment]
@BHoMBot check dataset-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check copyright-compliance

**Review by pawelbaran — APPROVED** [review]
LGTM now 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
