### PR TITLE
Code deprecated in 4.0 milestone removed

### LINKED ISSUE #1048: Remove code deprecated in 4.0 milestone
#### Description:

As in the title.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1048

### Test files

Not needed - simple removal of stuff.

### Additional comments

One method marked as to be removed (`XDocument` query) has been undeprecated (is there such a word?) because after a second look it seems not to be as useless as it looked before - better keep it than confuse the code and potentially the users IMO.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd I requested dispensation on documentation compliance because this PR does not concern documentation at all.

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@FraserGreenroyd @adecler could you please give me a hint why would versioning check fail on this PR? I have added MessageForDeleted in Versioning_Toolkit (https://github.com/BHoM/Versioning_Toolkit/pull/169), not sure what else could be done. Thanks!

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd @adecler could you please give me a hint why would versioning check fail on this PR? I have added MessageForDeleted in Versioning_Toolkit ([BHoM/Versioning_Toolkit#169](https://github.com/BHoM/Versioning_Toolkit/pull/169)), not sure what else could be done. Thanks!

The work done on Versioning Toolkit should be done on this PR instead in a local JSON file which is then pulled into versioning toolkit during the post build processes. @michaelhoehn had a similar problem on an LCA PR last milestone.

As for the documentation check, you need to add a description to a method. From 4.3 onwards, description attributes are now required on methods as a minimum. So either that needs adding in this PR, or a new issue needs raising to capture it before dispensation can be granted.

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@FraserGreenroyd I have added the missing description - after a closer look it turned out that it seems to be the only one missing the whole project well covered in general, so not worth pushing this to an issue.

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Would be good to wait for [this issue](https://github.com/BHoM/Versioning_Toolkit/issues/166) to be closed out before we merge this just to be safe. I don't foresee there being an issue, but better safe than sorry.

**Comment by pawelbaran** [comment]
Aye, fair enough - is this in the pipeline or waiting for its time @FraserGreenroyd? There is no big rush with this PR, but may require rebasing if kept hanging for too long (it touches .csproj eh).

**Review by tiagogrossi — APPROVED** [review]
Love a good clean-up. LGTM once allowed.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
