### PR TITLE
Revit stability issues fixes

### LINKED ISSUE #1125: Revit 2020 Closing Upon Trigger of Pull and Push
#### Description:
Using Alpha 211116, 211119, works well with Revit 2021, when prompting the same push/pull for 2020 it closes the session of Revit with no warning, can provide test file as necessary 

I tested back to 211108- the issue isn't occurring with this alpha file

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1125

### Test files

@kayleighhoude's reproductive issue plus [standard Revit tests](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Additional comments

This is related to the change in assembly loading system introduced in https://github.com/BHoM/BHoM_Engine/pull/2681.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by kayleighhoude — APPROVED** [review]
Reviewed for both 2020 and 2021, issue seems to be resolved!

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
