### PR TITLE
Adapter buttons made always enabled

### LINKED ISSUE #1148: Adapter buttons should be active already in the main menu
#### Description:

Currently, the adapter buttons (activate/deactivate etc.) are grayed out when no models are open. It would be good to enable them in the main menu to improve the UX.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1148

### Test files

Open Revit and check whether the buttons are enabled before opening any document.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by michal-pekacki — APPROVED** [review]
Tested on different Revit versions with success! 👍

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
