### PR TITLE
Method checking whether an element has a visible parameter 

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
Closing  this one in favour of https://github.com/BHoM/Revit_Toolkit/pull/1390

**Pull request closed without merging**
