### PR TITLE
Tweak of StringValue method to return actual string as shown by Revit

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Review by tiagogrossi — DISMISSED** [review]
Change is working in linked PR, nice code modifications.

**Review by michal-pekacki — APPROVED** [review]
LGTM 👍

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Review by tiagogrossi — APPROVED** [review]
Still LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
