### PR TITLE
Change method name for compliance

### LINKED ISSUE #537: Revit_Toolkit: ToBHoMObjects(ProjectInfo) method is incompliant
#### Broken rules:

- File name is unrelated to method name
- There are multiple hard-coded parameter names that should be migrated to `MapSettings`

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #537 

### Test files
Existing and code review

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
> `FromRevit` is even less compliant than `ToBHoMObjects` imo... All Revit->BHoM convert names start with _ToBHoM_ prefix, my point in the issue was that `ToBHoMObjects` does not tell what sort of convert is that (it could be literally anything), while the filename is quite explicit. Maybe it could be something like `ToBHoMBuilding`?

`ToBHoM` is incompliant to the guidelines, all convert methods should start with `To` or `From` and not be `ToBHoM` or `FromBHoM` because BHoM is implicit, so the conversion should always be `ToSoftware` or `FromSoftware`.

> BTW, this will conflict with #551, which was raised a few minutes earlier 🐒

Whoever gets approvals first wins :wink:

**Comment by pawelbaran** [comment]
> > BTW, this will conflict with #551, which was raised a few minutes earlier 🐒
> 
> Whoever gets approvals first wins 😉

I will block this one forever then ⚔️ 

And seriously, is that stated somewhere that the names should be `ToSoftware` or `FromSoftware`? If it is a general, stated rule, then I am happy to align - in such case I would opt for closing this PR and renaming all methods in one, isolated action.

**Comment by pawelbaran** [comment]
Thanks @FraserGreenroyd 
[Convert Method Naming Convention](https://github.com/BuroHappoldEngineering/BuroHappold_documentation/wiki/IsValidConvertMethodName)

**Comment by FraserGreenroyd** [comment]
Discussed with @pawelbaran over Skype and shown him compliance documentation that fulfils the above.

Am happy to go with a mass renaming, so have reverted that change in this PR, and will have a separate issue raised for compliance of Convert method names.

**Pull request merged**
