### PR TITLE
Aligning with changes to panel creates

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/974
https://github.com/BHoM/BHoM_Engine/pull/1942
   
### Issues addressed by this PR

Aligning with changes to Structure_Engine

### CODE REVIEW

**Review by peterjamesnugent — APPROVED** [review]
LGTM from a Structures perspective - compiles for 2018, 2019 and 2020.

**Review by FraserGreenroyd — APPROVED** [review]
Approving from the BEnv perspective at request of @IsakNaslundBh - this does not impact us negatively so we're happy :smile:

**Review by pawelbaran — APPROVED** [review]
LGTM by the looks of the code

**Pull request merged**
