### PR TITLE
Revit toolkit issue312 migrating to physical objects

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/502
https://github.com/BHoM/BHoM_Engine/pull/1018

### Issues addressed by this PR

Closes first part of #312 targeting Framing elements. In agreement with @ZiolkowskiJakub this PR will only solve for framing elements and he will raise a separate branch for physical roof/floor/wall

Changed the Revit toolkit from pulling structural FramingElements to physical IFramingElements

Various fixes for orientation angles for Beams/Columns

**PLEASE NOTE THAT YOU WILL NEED TO UPDATE EXISTING SCRIPTS TARGETING REVIT AFTER THIS CHANGE WITH REGARDS TO PULLING AND PUSHING BEAMS AND COLUMNS TO/FROM REVIT**

### Test files

Push:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/_Macro/Push/Structure?csf=1&e=a8BdFM

Pull:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/_Macro/Pull/Structure?csf=1&e=XKDvtr

### Additional comments

@ZiolkowskiJakub please have a look and make sure you agree with the code structure.

@pawelbaran please ensure elements are pulled and pushed correctly

@michaldengusiak This should not happen, but please check that this has not affected capabilities on the env side

FYI @al-fisher , @rwemay  @jdarcyBHE @JosefTaylor @enarhi @emidio-piermarini @MartinHenriksen @johannaisak @njsmithies @alelom @FraserGreenroyd

### CODE REVIEW

**Comment by pawelbaran** [comment]
Plus a question: why do the files sit in the Structure, not Physical?

**Comment by pawelbaran** [comment]
@ZiolkowskiJakub I also have the 9 errors, these are crazy Nurbs curve-driven bars that for some reason are not accepted by Revit. Discussed with @IsakNaslundBh, can be ignored :-)

**Comment by IsakNaslundBh** [comment]
@pawelbaran thanks. Updated code with your two requests

@ZiolkowskiJakub , as pawel said. The ones failing are some nurbs curve that for some reason revit refuses to push. I have checked for non-planarity etc, but not sure what goes on with the ones failing. The curves I have used are fairly extreme though. Not sure if there is any other check I can do?

The API is happy, nothing is crashing before the transaction is done kind of..

**Comment by ZiolkowskiJakub** [comment]
Hi @pawelbaran and @IsakNaslundBh ,

I will Rebase and merge when this PR closed:
https://github.com/BHoM/BHoM/pull/502
https://github.com/BHoM/BHoM_Engine/pull/1018

**Pull request merged**
