### PR TITLE
Revit 2022 added to Readme.md

### LINKED ISSUE #1061: Update Wiki after the changes in mapping and convert on Pull are merged
#### What is missing/incorrect?

As suggested by @tiagogrossi in [this comment](https://github.com/BHoM/Revit_Toolkit/pull/1060#discussion_r681542547), it could be helpful to embed links to Revit_Toolkit Wiki in the messages that explain the complex concepts, such as mapping.

On top of that, the Wiki itself will need a refresh after the changes.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1061

### Test files

Revit 2022 added to Readme.md - testing of readme should not be needed 🐒 

### Additional comments

Wiki updated, this is the last bit.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by al-fisher — APPROVED** [review]
👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
