### PR TITLE
BHoM Version Button Added

### LINKED ISSUE #1296: Add BHoM Button Version
#### Description:

Add Button to UI to allow users to check which version they have installed.

### PR DESCRIPTION
**Pull request by travispotterBH**
### Issues addressed by this PR

Closes #1296 

Users can now check their current BHoM installation version.

### Changelog

- Currently installed BHoM version button added.

### CODE REVIEW

**Review by pawelbaran — COMMENTED** [review]
This looks good to me and I have no objections, however I would like @FraserGreenroyd to give the final green light as this PR crosses with both UI as well as CI/CD

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Rather than just displaying the BHoM version, I think this would serve well as being an `About` button which contains some key information users may find beneficial, such as links to the wiki documentation, etc.

**Comment by travispotterBH** [comment]
> Rather than just displaying the BHoM version, I think this would serve well as being an `About` button which contains some key information users may find beneficial, such as links to the wiki documentation, etc.
Current Info tab includes link to [Github wiki](https://github.com/BHoM/documentation/wiki) and [bhom.xyz](https://bhom.xyz/)
image

This PR adds: 
image
image


I believe the pre-existing information buttons, along with the addition will satisfy the request for links to wiki documentation.

**Comment by FraserGreenroyd** [comment]
But then why hide the version behind a button at all if that's all we're going to show? An about button can be expanded upon further to display installation date, it could show a more specific version (such as the alpha version if using an alpha over a beta).

If that link to the wiki is truly going to the BHoM Wiki (and not the Revit Wiki - which is the wiki that would be additionally pertinent on Revit Toolkit) then the link also needs updating to the new documentation link - http://bhom.xyz/documentation

**Comment by travispotterBH** [comment]
Roadmapped: https://github.com/BHoM/BHoM_Engine/issues/2971

**Comment by pawelbaran** [comment]
Sounds like there is a plan. I do not have a strong opinion here, so happy for you guys to lead, but please nudge me in case you need any support 👍 Meanwhile I will keep on lurking 🪱

**Comment by FraserGreenroyd** [comment]
Discussed with @travispotterBH offline, going to close this for now in favour of closing out the roadmapped issue https://github.com/BHoM/BHoM_Engine/issues/2971 to produce a good version of this. If that takes too long though then we will come back to this work as a default for beta - so branch not being deleted at this stage.

**Pull request closed without merging**
