### PR TITLE
Tolerances cleaned up

### LINKED ISSUE #536: Revit_Toolkit: Pass Tolerance from RevitSettings into geometry methods
#### Description:
Since each convert method started taking `RevitSettings` argument, it will be possible to pass its tolerance-related property instead of using hardcoded tolerance values.

Following the discussion in #809, resolution of this PR should include removing the hardcoded tolerance value from `ToRevit(this oM.Geometry.NurbsCurve curve)` method. FYI @LMarkowski

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #536

### Test files

No particular test files needed. I would recommend pushing floors or walls as well as framing from [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPush&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302) - that should cover the changes in `ToRevitCurves`, `ToRevitRoofBase` and `AdjustedLocationCurve`. I believe that the others are safe (in general, the changes should be non-harmful), but can prepare test files if required by the reviewers.

### Changelog

- Revit curve tolerances changed to native Revit values
- convert tolerances changed from hardcoded values to the ones stored in the `settings` argument

### Additional comments

`ArbitraryPlane` still uses the BHoM tolerance because it has nothing to do with Revit - it is required only to extract the normal using cross product mathematically.

On the comment on #536:
> Following the discussion in #809, resolution of this PR should include removing the hardcoded tolerance value from `ToRevit(this oM.Geometry.NurbsCurve curve)` method. FYI @LMarkowski

Manipulating the tolerance will not change the fact that in some cases the converted nurbs curve will come out heavily distorted. Therefore, I am happy to leave it as is for now and properly resolve it as explained in #866.

### CODE REVIEW

**Comment by pawelbaran** [comment]
One more commit made (Revit tolerances centralised in `BH.oM.Adapters.Revit.Tolerance` class + folder renaming), changelog updated accordingly. Ready to review 👍 

Side note: `RevitFilePreview` and `FamilyLibrary` belong to `BH.oM.Adapters.Revit.Generic` namespace that does not align with the current folder name (_Misc_) - that is going to be fixed (_Generic_ prefix to be removed from the namespace) once assembly numbers versions switch to 4.0 and Versioning is back.

**Review by LMarkowski — APPROVED** [review]
LGTM, both changes and further plans.

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
