### PR TITLE
Add `Create.Callout`

### LINKED ISSUE #1397: Add `Create.CalloutView`
#### Description:

Add method for creating new callout view.

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #1397 

Add method for creating callout view.

### CODE REVIEW

**Comment by michal-pekacki** [comment]
@BHoMBot check compliance

**Review by pawelbaran — APPROVED** [review]
Happy with the code and functionality - good addition to the code base 👍

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]
The tweak makes sense, happy to reapprove 👍

**Comment by michal-pekacki** [comment]
@BHoMBot check compliance

**Comment by michal-pekacki** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, installer, ready-to-merge

**Pull request merged**
