### PR TITLE
Revit_Core_Engine: Add functionality to create reflected ceiling plan

### LINKED ISSUE #1040: Add functionality to create reflected ceiling plans
#### Description:
Currently the view creation methods do not allow for reflected ceiling plans. A new method is required to do so.

### PR DESCRIPTION
**Pull request by tiagogrossi**
### Issues addressed by this PR

Closes #1040 

To complement the create view methods we need one to create reflected ceiling plan.

### Changelog
Adds `BH.Revit.Engine.Core.Create.ViewReflectedCeilingPlan`

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
LGTM 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check dataset-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check copyright-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
