### PR TITLE
Missing altconfigs for 2023 added

### LINKED ISSUE #1252: Revit 2023 support is missing
#### Description:

The latest installer doesn't seem to include Revit 2023 support.

#### How to replicate:

I installed it from the given links and verified it's the latest file.

#### Expected behaviour:

There should be new assemblies like Revit_Core_Engine_2023.dll after the install.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1252

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Review by vietle-bh — APPROVED** [review]
Approving this since it has passed the installer check. Will install again using the new installer tomorrow as well.

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
