### PR TITLE
Layer convert tweaks

### LINKED ISSUE #1003: Improve warnings on construction convert from Revit
#### Description:

Currently when the constructions get converted from Revit, there is almost no messages regarding the structure of the layers. What (at least) needs to be captured is:
- variable layer thickness
- decking

#### Test file:
_PullConstructions_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1003

### Test files

Test _PullConstructions.gh_ and _PullConstructions.rvt_ from [this SharePoint folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Changelog

- warnings added for unsupported deck and variable thickness layers
- layer convert moved from `Query` to `Convert` class

### Additional comments

This is a feature, so should not be merged before the Beta release.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by michal-pekacki — DISMISSED** [review]
Tested on different Revit versions with success! 👍

**Comment by pawelbaran** [comment]
After a slightly messy rebase, https://github.com/BHoM/Revit_Toolkit/pull/1163 has been opened to replace this PR.

**Pull request closed without merging**
