### PR TITLE
Remove PreviousVersion attributes for previous milestones

### LINKED ISSUE #951: Removal of PreviousVersion attributes
`PreviousVersion` attributes have been detected in this repo and should be removed for the start of the new milestone.

The following files have been identified to have outdated `PreviousVersion` attributes:

 - Revit_Engine\Create\Elements\DraftingInstance.cs
 - Revit_Engine\Create\Elements\ModelInstance.cs
 - Revit_Engine\Create\Requests\FilterTypesOfFamily.cs
 - Revit_Engine\Query\RevitEdges.cs

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #951

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective, will leave to discipline to merge.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by pawelbaran — APPROVED** [review]
LGTM

**Pull request merged**
