### PR TITLE
Framing elements stopped from being pushed with wrong length in case of default Start/End Extension param value not equal to zero

### LINKED ISSUE #1134: Framing elements get pushed with wrong length in case of default Start/End Extension param value not equal to zero
#### Description:

As in the title, if the default extension in the Revit project is not zero, the length of the bars may be wrong, as noticed by @enarhi.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1134

### Test files

Quickfix for @enarhi - hopefully able to test using your project work.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@FraserGreenroyd this is a 2-liner PR fresh off `main` - still, null-handling check is failing 😭 Let's get it dispensated to unblock pls.

**Review by enarhi — DISMISSED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4400456094

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
