### PR TITLE
New Revit identifiers added

### LINKED ISSUE #945: Add HostId to RevitIdentifiers
#### Description:

It is an easy win for all hosted elements that can be useful in multiple cases (as just proven during the conversation with @rboulton-BH). Important: `ModelInstance` already has a similar property, good to try avoiding the mismatch between the property and the information stored in the fragment.

To be done together with #963

### LINKED ISSUE #963: Add Workset to RevitIdentifiers plus a Query method
#### Description:

As in the title, it is a super important information that is missing now. To be done in one go with #945.

### LINKED ISSUE #973: Add link information to RevitIdentifiers
#### Description:

Probs link file will be most appropriate. To be resolved together with #945 and #963.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

Not direct dependency, but versioning needs to be run on https://github.com/BHoM/Versioning_Toolkit/pull/141.
   
### Issues addressed by this PR

Closes #945
Closes #963
Closes #973

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23977%2DNewIdentifiers&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - please note that full functionality requires rebuilding Versioning_Toolkit on https://github.com/BHoM/Versioning_Toolkit/pull/141.

### Changelog

- `Workset`, `HostId` and `LinkPath` properties added to `RevitIdentifiers` fragment
- `Query` methods extracting the above information from a `BHoMObject` added

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by LMarkowski — APPROVED** [review]
Code looks good and I didn't manage to break anything in the test file. Approving.

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
