### PR TITLE
`FamilyInstance_WorkPlaneBased` - fixed direction for null orientation value

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #

Fixed direction value for placing hosted elements on line elements (walls, ducts, pipes) if input orientation is null.

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
Changes make sense, thanks @michal-pekacki

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by michal-pekacki** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
