### PR TITLE
Update of IInstances improved to handle orientation and hosts

### LINKED ISSUE #931: Update of ModelInstances and DraftingInstances does not handle Orientation
#### Description:

In https://github.com/BHoM/Revit_Toolkit/pull/926, handling of `Orientation` has been added only to `Create` and `Read`, needs to be introduced to `Update` too.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #931

### Test files

_PushInstances.rvt_ and _PushInstances.gh_ from [this folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - I did my best to set up the tests in a granular, understandable way.

### Changelog

- update of IInstances improved to handle orientation and hosts
- minor refinements made to `Create.FamilyInstance` methods to fix the bugs caught when preparing the test scripts

### Additional comments

@michaelhoehn @enarhi @tiagogrossi @AndreBalasian I believe it might be worth for you to have a look at `Create.FamilyInstance` methods, which is my attempt to tame one of the prime evils of Revit, family instance creation - I tried to structure the methods in a problem-agnostic manner, so that they could be reused by others to avoid the lottery related to the application of [`NewFamilyInstance`](https://www.revitapidocs.com/2020/4f835512-a922-c7da-d389-3bdcb41a5660.htm?section=methodTableToggle) method.

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Checked all the test cases and everything seems to work as good as we can get it from Revit. 😉 
No major objections to the code. Everything LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd code compliance to be ignored as the errors are irrelevant

**Pull request merged**
