### PR TITLE
Handling of host information refined, support for FamilyInstances hosted on linked elements plus ToRevit convert for Architecture.BuildersWork.Opening added

### LINKED ISSUE #990: Introduce a way of applying host element information to pushed objects
#### Description:

Some BHoM objects pushed to Revit are meant to become hosted Revit elements, so they require the information about the host being passed to Revit somehow. Currently that has been the case only for `ModelInstances` and was resolved by using `HostId` property. However, that does not scale nicely, e.g. Physical reinforcement does not have (and will never have) such property, so currently a temp solution based on `CustomData` is used (see #956).

There is a need for an universal solution: my idea is to introduce a `RevitHostIdFragment` that could be added to virtually any object before push. Happy to hear others' opinion @alelom @IsakNaslundBh @LMarkowski (please stop me if this does not make sense 🐒).

### LINKED ISSUE #1012: Introduce converts for BH.oM.Architecture.BuildersWork.Opening
#### Description:

As in the title - to be figured out how to do this most smartly.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2705
https://github.com/BHoM/Versioning_Toolkit/pull/179

   
### Issues addressed by this PR

Closes #990
Closes #1012

### Test files

PR-specific tests on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231127%2DOpeningConverts&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4):
- _CreateUpdateIInstances_ is an updated standard test that includes the elements hosted on links
- _PullIInstances_ same as above, just for `Pull`
- folder _Openings_ contains a workflow that shows two concepts:
    - matching BHoM types with specific families and parameter mapping - on both `Push` and `Pull`
    - handling and leveraging the host information on `Push` and `Pull`

The above tests are meant to become the new versions of standard Alpha test files. Additionally _PerformanceTest_ verifies the execution speed of geometrical search, which seems to be quite satisfying.

On top of the above, verifying _UpdateType_ from the [standard test library](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) is recommended.

### Changelog

- `ToRevit` convert method for `BH.oM.Architecture.BuildersWork.Opening` added
- `RevitHostFragment` introduced to consistently store the information about host Id as well as its original document in case when it is a link
- `RevitIdentifiers` refined to reflect the changes in handling of host/link information
- `FindHost`  and `ContainingElement` methods added to enable geometrical search for host elements
- `Create.FamilyInstance` refined to accept host elements from linked models
- `Modify.SetLocation` refined to support host elements from linked models
- `LinkInstance` queries refined to support the above changes
- `HostId` query replaced with `HostInformation` to return both Id and document info
- `SetType` method cleaned up

### Additional comments

This is a massive PR, but was hard to split into smaller ones taken the mutual relationships between most changes - I will provide as many tests as possible to ease the pain of the reviewers.

There is one breaking change - `HostId` property has been removed from `RevitIdentifiers` fragment and moved to `RevitHostFragment`, but the values are not going to be copied over - this is because this would require versioning of all `IBHoMObjects`, which I guess would be super heavy.

@kayleighhoude @enarhi, among the test files there is a sample showing workflow with parameter and family mapping, which allows for pulling elements of wide categories (e.g. _Generic Models_ or _Mechanical Equipment_) and mapping them to particular BHoM types incl. transfer of parameters to properties - I believe this is going to be neat!

@ssiimmoonnee the concept of host search could be helpful in e.g. finding hosts for windows/doors - happy to pick this up in the next PRs!

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by kayleighhoude** [comment]
@pawelbaran this is going to be huge for so many workflows (to your question, I don't know of anyone using HostID in previous workflows), excited to dig into this for electrical teams doing a smarter copy monitor to our light fixtures when we have a lighting consultant (same for plumbing fixtures for the PH teams)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Review by michal-pekacki — APPROVED** [review]
Tested on different Revit versions with success 👍

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@FraserGreenroyd what is the chance the null-handling check is simply wrong? Or could we make it at least return an informative message? I was scrolling through the entire chain of PRs a few times and feel like another hour can be used more efficiently than doing this yet another time...

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by michal-pekacki — APPROVED** [review]
LGTM 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
