### PR TITLE
`Create.FamilyInstance` - activate fix

### LINKED ISSUE #1365: `FamilyInstance` crashes - family symbol is not active
#### Description:

`FamilyInstance` method crashes when placing inactive family symbols:

image

#### Steps to reproduce:

Use `FamilyInstance` method to place family that was not used in the model before.

#### Expected behaviour:

Family Symbol should be activated before creating.

### PR DESCRIPTION
**Pull request by michal-pekacki**
### Issues addressed by this PR

Closes #1365 

Added family symbol activate to avoid crashing if not activated.

### CODE REVIEW

**Review by pawelbaran — COMMENTED** [review]
Happy with the code changes @michal-pekacki, but could you pls add the same tweak to adaptive component create method? Thanks!

**Review by pawelbaran — APPROVED** [review]
Happy to approve the changes following the review and quick testing.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. Renew the cache

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. Renew the cache

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. Renew the cache

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. Renew the cache

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by travispotterBH** [comment]
@pawelbaran  Was taking a look at this as part of other work and noticed that it seems that a `document.Regenerate()` is required after an `familyInstance.Activate()` to see the benefits of its use. A `document.Regenerate()` can only be used within a transaction. So does it make sense to cover this call here as it seems that it might give the false impression that the geometry has ben filled? 
image
I may be misunderstanding the documentation at revitapidocs.com though.. https://www.revitapidocs.com/2023/b4e09402-f6cd-3f48-d01e-ecb87375bac5.htm

https://www.revitapidocs.com/2023/22468e2c-9772-8478-0816-c9759aa43428.htm
image

**Comment by pawelbaran** [comment]
I must say that I have learnt about activation status of `FamilySymbol` empirically so I may be wrong, but from what I reckon, the only situation it is inactive is when the family type gets loaded, but not used yet.

Regardless, this should not matter in the context of this PR: we simply make sure the symbol is active when calling `Create.FamilyInstance`. Also not sure if I see the problem with activation requiring transaction - creation of a Revit element needs it so we should assume that `Create.FamilyInstance` will always be wrapped in one.

**Comment by travispotterBH** [comment]
> creation of a Revit element needs it so we should assume that `Create.FamilyInstance` will always be wrapped in one.

Maybe we need to add `.Regenerate()` into this method.

**Comment by pawelbaran** [comment]
> Maybe we need to add `.Regenerate()` into this method.

Did you check if we need? The method works as intended from what I know.

**Comment by michal-pekacki** [comment]
`.Regenerate()` can freeze model for a very long time, especially models with many linked files - I would only use it if necessary.

**Pull request merged**
