### PR TITLE
Remove PreviousVersion Attributes

### PR DESCRIPTION
**Pull request by BHoMBot**
Remove `PreviousVersion` attributes for pre-5.0 versioning

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a DevOps perspective, will leave merge to toolkit lead or will be merged automatically on 29th September 2021.

**Review by pawelbaran — APPROVED** [review]
LGTM, thanks @FraserGreenroyd 👍

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
