### PR TITLE
Support for Revit 2018 and 2019 removed

### LINKED ISSUE #1412: Remove support for Revit 2018 and 2019
#### Description:
As in the title, following the agreements made earlier in 2023. FYI @FraserGreenroyd

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1412

### Test files

Standard test procedure.

### Additional comments

The scope of this PR, although limited, touches quite a lot of files on different levels - please review the changes **carefully** to avoid us sneaking in any bugs that could hit us at the end of the milestone 👍

### CODE REVIEW

**Review by travispotterBH — DISMISSED** [review]
As discussed. Does the job.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@FraserGreenroyd am I correct we need to tweak the bot/installer to make the check pass?

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd am I correct we need to tweak the bot/installer to make the check pass?

Sorry @pawelbaran only just caught up with things.

You are correct though as I think you've found on the `altConfigs` for this repo for `core`. We also need to update the bot installer as well but we can do that once we're fully happy with this.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by vietle-bh — APPROVED** [review]
Tested and it worked.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
All good from previous reviews, approving to merge for deployment and further testing via alphas.

**Pull request merged**
