### PR TITLE
Handling of links improved

### LINKED ISSUE #1010: Link handling improvements
#### Description:

A few improvements could be introduced to the way in which links are handled in Revit_Toolkit:
- make it possible to handle links by their instance name
    image
- enable pulling all links from model and the select the one to pull from

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1010

### Test files

_MultipleLink_Requests.rvt_ and _MultipleLink_Requests.gh_ in [standard Alpha test scripts](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests%2FLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4). For those extra curious about versioning of `FilterByLink`, please feel free to check _Link_StandardRequests.rvt_ and _Link_StandardRequests.gh_ from the folder above.

### Changelog

- `FilterLinkInstance` request added
- ability to pull from Revit links using `FilterByLink` extended to accept link instance's _Name_ parameter or `ElementId`
- `Create` method creating `FilterByLink` based on previously pulled link instance added
- case sensitivity manipulation enabled for link-related requests

### Additional comments

This should conclude any link-related tasks for this Milestone.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Review by LMarkowski — APPROVED** [review]
I've checked the code and multiple link requests test files from alpha folder.
Also was extra curious and checked linked standard requests.
All worked good and lgtm. Approving!

**Comment by LMarkowski** [comment]
@BHoMBot check installer

**Comment by LMarkowski** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2364074036

**Pull request merged**
