### PR TITLE
Push/pull of line-based draftingInstances and filled regions enabled

### LINKED ISSUE #505: Revit_Toolkit: Support for Filled Regions and line based Detail Items
#### Description:

As in the header, support is missing for some types of detail items, incl. Filled Regions.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

- [Geometry_Engine #1429](https://github.com/BHoM/BHoM_Engine/pull/1429)
   
### Issues addressed by this PR

Closes #505

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue505%2DSupportForFilledRegionsAndLineBasedDetailItems) - all is set up on _LEVEL 00 - GA_ view, as a minimum I would recommend pushing everything prepared in the GH script and then pulling all objects of type `DraftingInstance` (also prepared in the script).

### Changelog

- Push/pull of Filled Regions and line based Detail Items has been enabled.

### Additional comments

Some macro test pulling a hatch-based load plan would be great - @IsakNaslundBh @kThorsager anything comes to your mind?

### CODE REVIEW

**Comment by pawelbaran** [comment]
@FraserGreenroyd could you please have a look at the failing checks? I have tried to track it myself, but failed. What can be a hint: I needed to locally merge master into [BHoM_Engine #1429](https://github.com/BHoM/BHoM_Engine/pull/1429), before doing that I could not instantiate Revit_Adapter:

image

**Comment by FraserGreenroyd** [comment]
The compiling issue on AppVeyor was caused by the bug which was fixed here: https://github.com/BHoM/BHoM_Adapter/pull/183

I have rerun CI and they're coming back green so all resolved on that front @pawelbaran :smile:

**Comment by pawelbaran** [comment]
Copyright set to 2020.

@kThorsager could you please re-approve?
@FraserGreenroyd @MajaLindroth @IsakNaslundBh is there any chance one of you reviews this? I have another huge PR almost ready in the pipeline...

**Pull request merged**
