### PR TITLE
Enum reflecting Revit categories added and category matching mechanism refactored

### LINKED ISSUE #1226: Revit_oM? : Revit Built-in Categories as Enum
#### Description:

Per conversation with @pawelbaran it could be helpful for new users into the BHoM to be able to select the Revit category they wish to pull by a dropdown instead of typing. I imagine this as an enum. 

Not sure where best this would live though given that it is a UI specific category list, though it would be helpful in both Excel and Grasshopper pull from Revit workflows. 

image

### LINKED ISSUE #1295: Update BuiltInCategory Method to include all built in categories
#### Description:

Current method for scraping built in categories from Revit does not include all built-in-categories, rather just a subset. 
For Example: Revisions is not available by scraping categories from `document.settings.Categories`
MicrosoftTeams-image (14)
MicrosoftTeams-image (15)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1226
Closes #1295

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231312%2DCategoriesAsEnum&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open your fav model and try pulling by category chosen from dropdown. Dropdown UX improvement has been proposed in https://github.com/BHoM/Grasshopper_UI/pull/677 and https://github.com/BHoM/BHoM_UI/pull/450.

### Changelog

- `BH.oM.Revit.Enums.Category` added with all Revit categories along with human-readable labels in attributes
- category matching mechanism has been refined in a way that if a category is correctly added to the above enum, it will both appear in the UI dropdown as well as become available in `BH.Revit.Engine.Core.Query.BuiltInCategory(string, bool)`
- `CategoriesWithNames` method added that returns a collection of built in categories with correspondent labels that are consistently supported by the system

### Additional comments

Now we should be able to freely extend the list of supported categories @travispotterBH - for now I added `Revision` from the nonstandard ones.

### CODE REVIEW

**Comment by pawelbaran** [comment]
Ah, also the UI of the enums has been tweaked in https://github.com/BHoM/BHoM_UI/pull/448 @travispotterBH

**Comment by pawelbaran** [comment]
I have just pushed a [surgical commit](https://github.com/BHoM/Revit_Toolkit/pull/1312/commits/f35b9aa96720a78422ce2c07854916d7830c7acf) that is probably easiest to review in isolation - it is only removal of redundant method parameters, so you should only see minor removals, no other changes.

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by vietle-bh** [comment]
I've gone through the code and all looks good. Having an issue with obtaining a Rhino license on my laptop though, so will test this in Grasshopper as soon as IT sorts Rhino out for me 👍

**Comment by pawelbaran** [comment]
Thanks for review @vietle-bh, on your comments:
- the 3-4s delay is a bug of Grasshopper itself, we can't fix it without a major intervention in Grasshopper_UI - I have added an extra search bar via https://github.com/BHoM/BHoM_UI/pull/450 and https://github.com/BHoM/Grasshopper_UI/pull/677
- the items are ordered alphabetically based on `DisplayText` attribute - you need to build https://github.com/BHoM/BHoM_UI/pull/448 to see the correct labels 👍

**Review by vietle-bh — APPROVED** [review]
The category list is sorted alphabetically and works like a dream with searches 😍 

image

image

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Pull request merged**
