### PR TITLE
Revit_Core_Engine: Fix MEP linear objects converts

### LINKED ISSUE #1036: Add changes from MEP_oM linear elements refactor
#### Description:
The linear elements in MEP_oM are being refactored as per this [link](https://github.com/BHoM/BHoM/pull/1248). Some properties have changed which impacts the converts `FromRevit`.

### PR DESCRIPTION
**Pull request by tiagogrossi**
### NOTE: Depends on 
[BHoM/BHoM#1248](https://github.com/BHoM/BHoM/pull/1248)

   
### Issues addressed by this PR

Closes #1036

Simplifies the converts `FromRevit` for the linear MEP objects (cable tray, duct and pipe).

### Test files
Test files `PullCableTrays.rvt` and `PullCableTrays.gh` are [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=LinkFilename&isAscending=true&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull)

### Changelog
Modified `BH.Revit.Engine.Core.Convert.CableTrayFromRevit`
Modified `BH.Revit.Engine.Core.Query.LocationCurveMEP`

### Additional comments
A follow up PR will address the addition of the MEP fitting object convert. This PR has simplified the converts of linear objects to not take fittings in consideration.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by pawelbaran — DISMISSED** [review]
I like the changes code-wise, getting rid of massive loops is always a plus 👍 

Test files are missing, so can't speak for the functionality part and would prefer not to merge before we get a hands-on proof (maybe the existing Beta test files would be enough @tiagogrossi?).

Regarding the two failing checks, I believe it should be fine to merge regardless of them:
- `null-handling` - this PR is does not concern this problem by itself, while the code does not get any worse than it was, so I would say let's merge and resolve null handling in a separate, isolated thread
- versioning - this code does not get exposed in the UI, so as long as the dependencies do not get broken, it should be OK

...but would be good to hear @FraserGreenroyd's opinion on that too.

**Review by pawelbaran — COMMENTED** [review]
Changing my approval to comment no to merge before the functionality test is run.

**Comment by tiagogrossi** [comment]
Thanks @pawelbaran , I have edited the PR description with the link to test files.

**Review by pawelbaran — APPROVED** [review]
This PR is alters the behaviour compared to `master` by removing the short segments that get created in place of fittings. This, however, is an improvement in long-term because it makes the convert more structured (the convert only covers the actual MEP element, not its fittings - the latter to be converted separately). Therefore, I am happy with the interim change, as long as @kayleighhoude does not veto it because of existing scripts.

This PR still needs to wait for oM and Engine, which hopefully will fix the failing checks 👍

**Comment by michaelhoehn** [comment]
@BHoMBot check null-handling

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check documentation-compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd looks like we got this green finally. Could you please unblock?

@tiagogrossi @michaelhoehn are we happy to merge once unblocked?

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed through with @michaelhoehn and all is good now.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
