### PR TITLE
FilterEverything request introduced, FilterDescription query added, FilterByParameterNumber refined

### LINKED ISSUE #1068: Implement FilterEverything request
#### Description:

Sometimes it is needed to filter all elements from a Revit model - a dedicated request would be welcome.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1068

### Test files

Files to test the changes in `FilterByParameterNumber` are placed on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2FBuroHappold%5FRevit%5FToolkit%2D%23296%2DNEWScenarioBasedRoutinesPrototype&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

`FilterEverything` can be tested on any model - just be careful as pull of everything can take some time ;-)

### Changelog

- `FilterEverything` request introduced 
- `FilterDescription` query added
- `FilterByParameterNumber` extended with `ConvertUnits` property

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by tiagogrossi — APPROVED** [review]
Also LGTM, nice addition of string compare .

**Comment by tiagogrossi** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
