### PR TITLE
Align to namespace change in Socket Toolkit

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/Socket_Toolkit/pull/83

### Test files
Just make sure it still compile once you have changed on both PRs

### Additional comments
@pawelbaran , there was no open PR that would interfere with this but let me know if it is a problem. We can easily delay this if needed.

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Checks have passed so I'm happy - @pawelbaran can confirm the bit about clashing stuff.

**Review by pawelbaran — APPROVED** [review]
LGTM

**Review by alelom — APPROVED** [review]
LGTM!

**Pull request merged**
