### PR TITLE
Create class of Revit_Core_Engine covered with descriptions

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

2nd part of #596

### Test files

This PR is only about descriptions.

### Additional comments

In the coming days, this PR will be followed with sister PRs covering other classes of Revit_Core_Engine.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by tiagogrossi — APPROVED** [review]
Looks good, nice addition of information.

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
