### PR TITLE
.NET Framework version upgraded to 4.7.2

### LINKED ISSUE #1017: Upgrade minimum .NET Framework version to 4.7.2
#### Description:

Revit_Toolkit started failing to build due to indirect dependency (through Environment_Engine) on Kellerman Compare .NET Objects, which is built against .NET Framework 4.7.2 (@LMarkowski @FraserGreenroyd please correct me if I messed it up, typing from memory).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1017

### Test files

Try whether the repo builds against fresh alpha (without building any other repos from source), then check on arbitrary test script from [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - if it works, all is good.

### Additional comments

@adecler you might be interested in this one, it is a bit of a hotfix not sure if it really necessary or just hiding symptoms tbh (@FraserGreenroyd may know better).

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by LMarkowski — CHANGES_REQUESTED** [review]
So now I see it was already picked up by the CI tests, but the toolkit doesn't build in `Debug`, `Debug2018`, `Release` and `Release2018` configurations. 
However on other configs everything works fine including the test scripts.

PS, maybe this is a good chance to get rid of `Debug` and `Release` configs? Am I correct that they just duplicate the `2018` ones?

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
Ok it was me doing stuff last minute before the weekend without bothering to test it properly. Apparently, Revit 2018 assemblies are still built against .NET Framework 4.5.2 - I was convinced it is already 4.7 at least, so did not action them. I have just pushed a commit to fix that.

Regarding @LMarkowski's comment:
> 
PS, maybe this is a good chance to get rid of `Debug` and `Release` configs? Am I correct that they just duplicate the `2018` ones?

I am a big fan of that and would have done that long time ago, but we still need versionless `Debug` and `Release` configs for CI/CD reasons, am I correct @FraserGreenroyd?

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
> I am a big fan of that and would have done that long time ago, but we still need versionless `Debug` and `Release` configs for CI/CD reasons, am I correct @FraserGreenroyd?

You are 👍

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Review by LMarkowski — APPROVED** [review]
Ok, now all configs build correctly on today's alpha and the toolkit itself works fine (tested on pushing columns in Rvt_2020).
For me that's enough, but others may want to add something.

**Comment by pawelbaran** [comment]
Thank you @LMarkowski. I will do some more testing before merge.

**Comment by pawelbaran** [comment]
I am closing this PR as well as the related issue - rebuild on today's Alpha against 4.5.2 works perfectly fine 👍 No need to upgrade.

**Pull request closed without merging**
