### PR TITLE
Calling Create method rather than constructor for MaterialComposition

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

Does not depend on for compilation, but done in alignment with https://github.com/BHoM/BHoM/pull/1341 and https://github.com/BHoM/BHoM_Engine/pull/2733.
Checks done in constructor migrated to engine Create method.   

### Issues addressed by this PR

Calling Create method rather than constructor straight away to ensure checks and potential error messages are raised appropriately

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Review by pawelbaran — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed in conjunction with the PRs on oM and Engine and matches with expectations. Review from @pawelbaran also so this is good to go to `main`.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
