### PR TITLE
Add method to query closest element from another element (REBASE)

### LINKED ISSUE #1123: Add method to query the closest element from another element
#### Description:
Suggesting new method to query what is the closest element of a certain category to another element, enabling searching on linked files.

### LINKED ISSUE #1133: Can't pass unloaded links in Query.LinkInstance
#### Description:
When querying the document of a LinkInstance it has to be loaded, otherwise it results in null. While the result is expected, in this particular method `Query.LinkInstance` it uses LINQ to query the path of the document, crashing when the expected null comes.

### PR DESCRIPTION
**Pull request by tiagogrossi**
### Issues addressed by this PR

Closes #1123 
Closes #1133

Adds a method to query the closest element from another element, with the ability to filter by category and distance search radius.

### Test files
N/A

### Changelog
Added `Core.Query.ClosestElement`
Added `Core.Query.HasLocation`

### CODE REVIEW

**Comment by tiagogrossi** [comment]
@BHoMBot check compliance

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Review by pawelbaran — DISMISSED** [review]
LGTM

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check null-handling

**Review by pawelbaran — DISMISSED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4408475897

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
