### PR TITLE
Replace RevitMaterialTakeoff with new class in phsyical_oM

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1423
https://github.com/BHoM/BHoM_Engine/pull/2897
https://github.com/BHoM/Versioning_Toolkit/pull/204
   
### Issues addressed by this PR

To avoid the overlapping concepts mentioned in https://github.com/BHoM/BHoM/pull/1423#pullrequestreview-1085151886 , the Fragment in revit has been removed and versioned and replace with the new Fragment class.

Methods for extracting this have been renamed, moved to Matter_Engine and versioned.

### CODE REVIEW

**Review by alelom — COMMENTED** [review]
Code changes look good to me. Cannot test at the moment as Revit is not working on my machine.

**Comment by pawelbaran** [comment]
Thanks @IsakNaslundBh for the reply. As discussed in the call, my bad in testing versioning - must have not rebuilt Versioning_Tk correctly after jumping between `main` and this branch. So I take back my comment on functionality.

Regarding naming, good chat made offline, see [this comment](https://github.com/BHoM/BHoM_Engine/pull/2897#pullrequestreview-1154583075) to see my thoughts.

Happy to approve based on the above points as well as more testing made 👍

**Review by pawelbaran — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Review by pawelbaran — APPROVED** [review]
Re-approving based on my previous message - dear almighty @BHoMBot please accept this comment as a proof of the PR being reviewed and tested 😆

**Pull request merged**
