### PR TITLE
.csproj files switched to SDK style

### LINKED ISSUE #1282: Make the .csproj files BHoM-compliant
#### Description:

As in the title, currently project compliance check returns a series of warnings that could be cut down by tweaking the .csproj files - a good one to tick off during the dev slowdown planned for January.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1282

### Test files

Remove all BHoM/Revit specific resources from your system:
- addin file _%appdata%\Autodesk\Revit\Addins_
- resources, assemblies etc. from _%programdata%\BHoM_

Build from source and check if things get added where required. Additionally, installer link to be shared later.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by vietle-bh — APPROVED** [review]
All Debug & Release build configs worked. No error when testing random features in Revit 2020 to 2023.

**Review by michal-pekacki — APPROVED** [review]
Tested in different Revit versions without issues 👍

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10698655794

Dispensating as agreed https://github.com/BuroHappoldEngineering/Revit_UI/pull/117#issuecomment-1385080957

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 10698655794

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
