### PR TITLE
Update Assembly Version

### LINKED ISSUE #1004: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `4.2.0.0` for all `AssemblyInfo.cs` files within this repository for the 4.2 milestone.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #1004

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. Will let discipline merge when happy.

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd compliance fails, can this be merged? 🐒

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd compliance fails, can this be merged? 🐒

Yeah, it's only branch compliance that fails which is ok as that allows `check-installer` to report across all PRs saving us a bit of computation per PR :smile:

**Pull request merged**
