### PR TITLE
Wiki link updated

### LINKED ISSUE #1424: Update Wiki link
#### Description:
As in the title, Wiki link needs to be updated to bhom.xyz/documentation.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1424

### Test files

Open Revit and check if the adapter buttons work as expected.

### Additional comments

I could not stop myself from a little code tweak to avoid hardcoded class names.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by vietle-bh — APPROVED** [review]
Works like a dream 👍 

image

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
