### PR TITLE
Adapter UX improved

### LINKED ISSUE #257: Revit_Toolkit: Adapter having trouble attaching to Revit
Pull from Revit returns error "Failed to connect to Revit" after one of several conditions:

* two instances of Revit are open > error
    * after one is closed, 'active' toggled to try to re-set adapter > error
    * remaining instance of Revit closed, re-opened > success!
* Grasshopper and Rhino closed to install a package (lunchbox) and re-openned > error

Firstly, it seems that the error should be returned by the adapter and not the pull. Is that possible?
Secondly, can anyone reproduce these errors and can we improve the robustness of the adapter?

### LINKED ISSUE #792: Revit_Toolkit: Requirement for Update Ports
#### Description:
Upon rebuilding Revit Toolkit/downloading a new installer, requirement for "Update Ports" on RevitListen in order for objects to pull across. I've experienced this on both my machine and others.
image

### LINKED ISSUE #875: Add links to BHoM and Revit wiki etc. to new BHoM tab in Revit
#### Description:

Following comments from @ssiimmoonnee and @pawelbaran (https://github.com/BHoM/Revit_Toolkit/issues/257#issuecomment-707607622 ) thinking could be useful to add additional buttons to link to BHoM Revit Toolkit Wiki - as is valuable - as other wiki, website links

Much like we have in Excel toolbar:

image

@pawelbaran @tiagogrossi what do you think?

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 
https://github.com/BHoM/Socket_Toolkit/pull/85

On top of that, not direct dependency, but https://github.com/BHoM/BHoM_Installer/pull/97 needs to be merged before this PR in order to make the plugin install correctly from the installer (build from source should be fine).

### Issues addressed by this PR

Closes #257
Closes #792
Closes #875

### Test files

Not needed - in general, one needs to activate/deactivate/refresh the adapter, close/open Revit without notice and see how it behaves. Test files can be taken from the [test SharePoint folder](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302).

### Changelog

- default adapter behaviour on the Revit side changed from _Active_ to _Inactive_ - the user needs to explicitly activate it using the button in the _BHoM_ Revit tab
- the connection check has been refined and error messages made more clear
- the adapter-related UI has been moved to the _BHoM_ Revit tab and extended to consist of the following buttons:
    - _Activate_
    - _Deactivate_
    - _Update Ports_
    - Info buttons with links to Wikis and websites

### Additional comments

I have added a long list of reviewers to make sure this does not go unnoticed. For the ones interested but too lazy to build 😃 

RevitAdapter

### CODE REVIEW

**Comment by pawelbaran** [comment]
Following the discussion with @kayleighhoude, I've updated the port extraction/update descriptions, Wiki to be updated once this gets merged.

**Review by al-fisher — COMMENTED** [review]
Hi @pawelbaran - as mentioned think this is looking good. (and not least of all gives some much needed love to the previously very lonely and lost looking BHoM Revit Addin button 😄)

Suggested comment from our chat - I would skip the "Set Ports" dialogue on the initial clicking of the "Active" button.
99% of the time I think users will click straight through on OK (whether confused about the ports or not :smile: ) 

Your UI already allows the user to then click on "Update Ports" after activation if they need to or are expert users. So think skipping will be fine and mean a slicker experience and explanation for most users.

**Review by alelom — COMMENTED** [review]
Looks good to me from a code perspective too!

**Review by LMarkowski — COMMENTED** [review]
Agree with @al-fisher on the UX point.
Besides that everything looks good to me 😄

**Comment by pawelbaran** [comment]
Updated according to a very valid suggestion of @al-fisher 👍

**Review by LMarkowski — APPROVED** [review]
LGTM!

**Review by FraserGreenroyd — APPROVED** [review]
LGTM following review with @pawelbaran

**Pull request merged**
