### PR TITLE
Align with changes in Structure_Engine

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738

 ### Issues addressed by this PR

Align with removed methods from Structure_Engine
 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Pull request merged**
