### PR TITLE
Pull of BEnv elements stopped from returning duplicate elements

### LINKED ISSUE #739: Revit_Toolkit: pull of BEnv elements results in duplicate elements
#### Description:

When pulling BEnv elements, they sometimes get duplicated because they get pulled from both physical and analytical model.

@FraserGreenroyd @rboulton-BH FYI I have a fix for it ready to PR once https://github.com/BHoM/Revit_Toolkit/pull/737 is closed.

#### Test file(s):

[Model](https://burohappold.sharepoint.com/sites/Direction/designtechnology/Script%20Library/Forms/AllItems.aspx?csf=1&web=1&e=NiBGLn&cid=c7288618%2Ddbe3%2D46c6%2Dbdac%2D240283593d9d&RootFolder=%2Fsites%2FDirection%2Fdesigntechnology%2FScript%20Library%2F00339%5FBEnv%20Model%20Laundry%20Workflows%2F03%20Test%2FKHN&FolderCTID=0x012000877674B0FB94234BB2F1C82F2331EE6F) and [script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue739%2DDuplicateBEnvPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #739

### Test files

[Model](https://burohappold.sharepoint.com/sites/Direction/designtechnology/Script%20Library/Forms/AllItems.aspx?csf=1&web=1&e=NiBGLn&cid=c7288618%2Ddbe3%2D46c6%2Dbdac%2D240283593d9d&RootFolder=%2Fsites%2FDirection%2Fdesigntechnology%2FScript%20Library%2F00339%5FBEnv%20Model%20Laundry%20Workflows%2F03%20Test%2FKHN&FolderCTID=0x012000877674B0FB94234BB2F1C82F2331EE6F) and [script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue739%2DDuplicateBEnvPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
Hmm I've tried to fix it in one go, but could miss something. Are there any links in the model you are testing on?

**Comment by MajaLindroth** [comment]
Uploaded it here [Model](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FEnvironment%2FFrom%20MajaLindroth)
I also tried with the one you had as test model, it had a problem with one panel

**Comment by pawelbaran** [comment]
@MajaLindroth this seems to be fine, single Revit elements get split into multiple panels:

image

image

So I believe the PR is OK.

**Pull request merged**
