### PR TITLE
Unit type of pulled parameters tweaked

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231350%2DAddSupportForPrimitiveCollections&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - only parameters that are measured in units should have `UnitType` property assigned (particularly relevant in lower versions of Revit, where it always was `UT_Number`).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by vietle-bh — APPROVED** [review]
It works well:

image

**Comment by pawelbaran** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
