### PR TITLE
Section update issues resolved

### LINKED ISSUE #1050: Revit section update issue
#### Description:

Following @NRaffe1:

At the moment the process of updating section sizes isn't very clear or simple. 
image

Would be great if the complexity of this could be reduced.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1050

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231051%2DSectionUpdateBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@FraserGreenroyd I have requested dispensation for document compliance, this PR is only changing a single private method, not dealing with the public ones.  On top of that, the project the issue concerns is not exposed to the UI, ergo even less relevant.

**Review by NRaffe1 — APPROVED** [review]

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3102351202

**Pull request merged**
