### PR TITLE
Create methods for IRequests cleaned up

### LINKED ISSUE #994: Clean up the Create methods for IRequests
#### Description:

There is a number of Create methods that simply call the constructor with property assignment - this was needed for UI purposes in the past, more of a noise now, so could be deleted.

On top of that, a few method parameter descriptions could be improved.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #994

### Test files

- [problem-specific versioning test](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23994%2DCleanUpIRequests%2F%23994%2DCleanUpIRequests%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23994%2DCleanUpIRequests)
- _StandardRequests_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) should work as before

### Changelog

- `Create` methods for `IRequests` cleaned up

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
Approved on code review.

**Pull request merged**
