### PR TITLE
Unit conversion performance improved

### LINKED ISSUE #1303: Performance of converts could be speeded up significantly by caching unit type
#### Description:

Currently on every unit convert `BHoMUnitType` method is executed, resulting in redundant 2 `foreach` loops and one Linq query that seem to take up majority of the entire execution time. This becomes an issue in case of performance-sensitive converts. Quick solution is available - it should be relatively simple to cache units for each unit type instead of querying them every time.

Another level of optimisation would be to store the actual conversion factors as doubles, but this would make the code less readable and the change more painful - not sure if it is worth, depends on how much will the performance improve.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1303

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231329%2DUnitConversionPerformance&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Review by vietle-bh — APPROVED** [review]
It works well 👍 

image

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
