### PR TITLE
View solid and bounds fixed for sections without far clipping

### LINKED ISSUE #1455: ViewSolid and ViewBounds queries yield wrong results for sections with Far Clipping set to No Clipping
#### Description:

Setting `Far Clipping` property of a section to `No Clipping` means that the depth of the section is unlimited, so the solid and box of the view should follow.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1455

### CODE REVIEW

**Review by vietle-bh — APPROVED** [review]
It works perfectly 👍 

image

**Comment by vietle-bh** [comment]
Fun fact: Stepped sections will not follow our view solid, but who uses them anyway! 🤣 

image

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
