### PR TITLE
Minor tweaks and additions to the code base

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

A mashup of a few minor tweaks and additions that accumulated on my machine while working on different bits:
- Query method for elements tagged by a given tag
- consolidation of `ToSolid` internal convert
- method to get bounds of a group of Revit points (mirror of a Geometry_Engine method added to avoid converts to BHoM and back, performance reasons)

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by michal-pekacki — APPROVED** [review]
Changes make sense, happy to approve 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
