### PR TITLE
Deprecated 3.2 code removed

### LINKED ISSUE #949: Remove deprecated code older than 3.3
#### Description:

As in the title, quarterly cleanup.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #949

### Test files

Not needed.

### Changelog

- deprecated 3.2 code removed

### CODE REVIEW

**Review by FraserGreenroyd — DISMISSED** [review]
LGTM, looks all tidied up :smile:

**Comment by pawelbaran** [comment]
@BHoMBot check core

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Still LGTM

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Pull request merged**
