### PR TITLE
Support for Revit 2021 added

### LINKED ISSUE #717: Revit_Toolkit: Set up for Revit 2021
#### Description:

Revit 2021 has been released publicly, support needed.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #717

### Test files

I have successfully run all tests from [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302), more tests would be welcome.

### Additional comments

**!! Testing this PR will require installation of Revit 2021 and .NET 4.8 SDK !!**
If we do not find the users that could do that (@AndreBalasian @michaldengusiak?), I am happy to run a live test session on Teams 🤣

### CODE REVIEW

**Review by michaldengusiak — APPROVED** [review]
I run few test and works for me ,

I can see lots of warnings as I am missing some data sets..
I used to gbXML and manage to import to Tas

image


image

image

I can see shades are not recognized any more but we can use with Revit 2021  :)

I tested also with Panels
image

also works fine with SAM
image

**Comment by pawelbaran** [comment]
Thanks for the review @michaldengusiak! What do you mean by shades not being recognized any more? Does that mean they were recognized in 2020, but are not in 2021? I noticed BEnv models being pulled slower compared to previous versions of Revit (looks like Autodesk must have changed something in that field...), but the output seemed to be the same at the first glance.

**Comment by michaldengusiak** [comment]
@pawelbaran it was Shade recognition as part of Environment  -  but I guess you now clear all traces of previous workflows... so I suppose this is how it should work ;)

**Comment by pawelbaran** [comment]
Apart from the facade wall (the guy below) that has been improved to capture different panels in a single walls, I do not see any difference, when looking at you screenshots @michaldengusiak 🙊

image

**Comment by AndreBalasian** [comment]
Compiles and runs well.
Tried a test on GS and it looks good.
image

**Review by AndreBalasian — DISMISSED** [review]
Looks good to me, and a GS test worked.

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
I am blocking solely to handle the installer updates which would need doing before this gets merged 😄

**Review by FraserGreenroyd — APPROVED** [review]
Great work @pawelbaran

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Pull request merged**
