### PR TITLE
Support for Revit 2022 added

### LINKED ISSUE #1021: Add support for Revit 2022 when applicable
#### Description:

As in the title. Besides adding the necessary solution configs etc., it would be good to refactor all occurences of `#if (REVIT2020 || REVIT2021)` to `#if (REVIT2018 || REVIT2019)` to support the upcoming, higher versions of Revit.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1021

### Test files

Identical code has been reviewed in #1072 ([link to branch comparison](https://github.com/BHoM/Revit_Toolkit/compare/e7834195a4f64c2b16e346427281a7ab6141e454..dd69ef7122b7794db8b618dca068852149cbfe1a)).

### Changelog

- support for Revit 2022 added
- `DisplayUnitType` enum replaced with properties of the `UnitTypeId` static class
- `UnitType` enum replaced with properties of the `SpecTypeId` static class
- `UnitTypeId` and `SpecTypeId` classes implemented for Revit versions older than 2021 to support the changes above (the classes mimic the Revit API ones in Revit 2021 and above)
- `Parameter.DisplayUnitType`  property calls replaced with `GetUnitTypeId` method calls
- `Definition.UnitType`  property calls replaced with `GetSpecTypeId` method calls
- `GetUnitTypeId` and `GetSpecTypeId` methods implemented for Revit versions older than 2021 to support the changes above (the methods mimic the Revit API ones in Revit 2021 and above)

### Additional comments

Do not be afraid of the file change count - most of it is just renaming 🙈 

The changes embrace in this PR are listed in detail in section 1.3 of [this link](https://thebuildingcoder.typepad.com/blog/2020/04/whats-new-in-the-revit-2021-api.html).

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
Closing this one as the original started being happy again 👍

**Pull request closed without merging**
