### PR TITLE
String-based type update enabled

### LINKED ISSUE #1011: Enable string-based type update
#### Description:

Currently the user needs to pull family type and then supply it to the `SetRevitParameter` method, which is not super user friendly. A simple string-based type update would be welcome.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1011

### Test files

_UpdateType.rvt_ and _UpdateType.gh_ on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - the bottom update has been added to verify this PR.

image

### CODE REVIEW

**Review by LMarkowski — APPROVED** [review]
Code looks good and test file works correct. Really nice feature!

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Pull request merged**
