### PR TITLE
IsPrimaryDesignOption Wrapper

### LINKED ISSUE #1448: Add Method to check is element is within the primary design option
#### Description:

Per team discussions, provide wrapper method.

### PR DESCRIPTION
**Pull request by travispotterBH**
### Issues addressed by this PR

Closes #1448 

- add IsPrimaryDesignOption Wrapper

### CODE REVIEW

**Comment by travispotterBH** [comment]
@BHoMBot check required

**Comment by travispotterBH** [comment]
@BHoMBot  check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check versioning

**Review by pawelbaran — APPROVED** [review]
Happy to approve, thanks @travispotterBH

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 21121461554

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
