### PR TITLE
Support for Revit 2024 added

### LINKED ISSUE #1428: Add support for Revit 2024
#### Description:

As in the title, Revit 2024 is out and needs to start being supported by BHoM.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1428

### Test files

Standard test procedure

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check versioning
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — APPROVED** [review]
It works for Revit 2024 and earlier 👍

**Comment by pawelbaran** [comment]
Sorry @vietle-bh I needed to rebase this branch after the copyright header update done by DevOps. Could you please re-review? Nothing should change apart from copyright headers.

**Comment by pawelbaran** [comment]
...please have a look at [this](https://github.com/BHoM/Revit_Toolkit/compare/1445260b3e39b2fec1e692b27ff260b25ee240a4...3c75ac7c0515dbde2b4849ea8098213ba2dc8a03) to simplify the re-review process @vietle-bh 😃

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — DISMISSED** [review]
Reapproving following the rebase and after checking the same commits were re-applied 👍

**Review by FraserGreenroyd — APPROVED** [review]
Reapproving based on @vietle-bh review as last changes are rebases to help with the copyright headers which went in around this work so no functionality changes since @vietle-bh approval

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Pull request merged**
