### PR TITLE
Revit_Toolkit-Issue287-FamilySymbolOfStructuralFramingBug

### LINKED ISSUE #287: Revit_Toolkit: FamilySymbol of StructuralFraming bug
Following fix needed:

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #287 

### Test files

No test file as the fix is quite obvious.

### CODE REVIEW

**Comment by ZiolkowskiJakub** [comment]
Will be merged when approved by @IsakNaslundBh

**Comment by FraserGreenroyd** [comment]
Discussion in BHoM call agrees that Test Files are required for Push and Pull operations for both Structures and Environments to help aid the changes to Revit Toolkit.

**Actions**
@IsakNaslundBh to test this PR
@jdarcyBHE to work with @IsakNaslundBh and @pawelbaran to prepare some general test files for Structures moving forward
@FraserGreenroyd and @michaldengusiak to prepare some general test files for Environments moving forward

**Comment by IsakNaslundBh** [comment]
@JosefTaylor to create test script for pushing beams and columns of various types.

**Comment by ZiolkowskiJakub** [comment]
Hi @JosefTaylor,

Please look at PR #303 which may be helpful to create test script.

@pawelbaran @IsakNaslundBh

**Comment by ZiolkowskiJakub** [comment]
Hi @IsakNaslundBh,

All good with you? Can we merge this?

**Comment by ZiolkowskiJakub** [comment]
In case of general test files:

Test script issue has been separated and rised here #261

**Pull request merged**
