### PR TITLE
Conformal transformation bug fixed in geometry primitives query

### LINKED ISSUE #1484: Geometry Primitives - conformal transform bug
#### Description:

`Query.GeometryPrimitives` raises exceptions on not conformal transofrm:

image

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1484

### Test files

Edge case captured by @michal-pekacki in one of the project models - to be tested against it.

### CODE REVIEW

**Review by michal-pekacki — APPROVED** [review]
It works as it should (changing edge case transform to conformal):

image

image

**Comment by michal-pekacki** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by michal-pekacki** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
