### PR TITLE
Refactor code from Environments perspective

### LINKED ISSUE #631: Revit_Toolkit: BH.UI.Revit.Engine.Query.HostedBuildingElements is never used
As in the title: `BH.UI.Revit.Engine.Query.HostedBuildingElements` is never used. Could we make sure that it is removed in 3.2 if not needed @FraserGreenroyd?

### LINKED ISSUE #634: Revit_Toolkit: Remove IsExternal, IsInternal and IsShade
#### Description:

Following methods are completely unrelated to Revit and should be moved elsewhere.
- `BH.Engine.Adapters.Revit.Query.IsExternal`
- `BH.Engine.Adapters.Revit.Query.IsInternal `
- `BH.Engine.Adapters.Revit.Query.IsShade`

### LINKED ISSUE #643: Revit_Toolkit: centralize OriginContextFragment queries around Query.OriginContext method
#### Description:

Atm `OriginContextFragment` is being created from scratch in every convert method. A lot of boilerplate could possibly be avoided by centralizing it as `BH.UI.Revit.Engine.Query.OriginContext`.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #634 
Fixes #631 
Fixes #643 

### Test files
Existing test scripts

### Changelog
 - Deleted `IsExternal` query method
 - Deleted `IsInternal` query method
 - Deleted `IsShade` query method
 - Deleted `HostedBuildingElements` query method
 - Tidy up `OriginContextFragment` creation

### Additional comments
Although this PR does not impact structures, I am requesting review from @kThorsager to provide a quick overview to confirm.
@MajaLindroth is requested review to confirm Environment workflow.
@pawelbaran is requested review as Toolkit Lead and original issue raiser to ensure everything is caught as appropriate.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@kThorsager can you confirm if you are giving this a review before we merge? I presume you are :smile:

**Comment by kThorsager** [comment]
Yeah, I'll review to be on the safe side

**Pull request merged**
