### PR TITLE
MEP element orientation issues fixed

### LINKED ISSUE #1410: MEP element orientation issues
#### Description:

@michal-pekacki identified that in some cases `OrientationAngle` query returns inconsistent results (sign changing between each run) for ducts, pipes etc., caused by the random order in which `Connectors` are returned by Revit API.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1410

### Test files

Standard MEP element pull test procedure

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by michal-pekacki — APPROVED** [review]
Tested and it works, happy to approve 👍

**Comment by michal-pekacki** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
