### PR TITLE
Extract the external curve loop query to its own method

### LINKED ISSUE #1496: Extract the logic for finding a face's main CurveLoop
#### Description:

The conversion from a Revit face to a BHoM one in https://github.com/BHoM/Revit_Toolkit/blob/develop/Revit_Core_Engine/Convert/Geometry/FromRevit/Surface.cs involves finding the main external curve loop of that face. I have a tool that wants to use this extraction logic without calling `FromRevit(this PlanarFace face)` because `List<ICurve> internalBoundaries = crvLoops.Where(x => x != externalLoop).Select(x => x.FromRevit() as ICurve).ToList();` can be slow on large datasets.

Let's move this external loop extraction logic to its own method.

### PR DESCRIPTION
**Pull request by vietle-bh**
### Issues addressed by this PR

Closes #1496

Extracted the external curve loop query to its own method

### Test files

I simply cut & pasted the relevant code to a new file, so hopefully just code review will be enough!

### CODE REVIEW

**Comment by vietle-bh** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check versioning 
@BHoMBot check installer

**Comment by vietle-bh** [comment]
@BHoMBot check versioning 
@BHoMBot check installer

**Comment by vietle-bh** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by pawelbaran — APPROVED** [review]
Changes make sense, happy to approve the refactor 👍

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
