### PR TITLE
CODEOWNERS file removed

### LINKED ISSUE #1170: Remove codeowners file
This toolkit is not transdisciplinary that would require a codeowners file anymore, so the file can be removed to tidy up the repo and the PR tagging going forward.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1170

### Test files

Not affecting the code.

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Does as it says on the tin. Lovely jubbly.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5004761878

**Pull request merged**
