### PR TITLE
Opening surface edge case bug fixed

### LINKED ISSUE #958: Opening surface edge case bug
#### Description:

When pulling an opening, `OpeningSurface` method is called that compares the plane host geometry before and after removal of the opening. It may happen (of course it happened to the user) that the opening gets deleted as a subpart of another element that is removed in order to extract the plane host geometry. In other words: a wall hosts an element that hosts an opening, the element gets removed in order to extract the plane host geometry, then Revit looks for the opening and voila! we have a problem.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #958

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23958%2DOpeningSurfaceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### Changelog

- opening surface edge case bug fixed

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check copyright

**Comment by pawelbaran** [comment]
@BHoMBot you there?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
LGTM on code review, adding a try/catch is simple enough :smile:

**Pull request merged**
