### PR TITLE
Removed room/space geometry bug fixed

### LINKED ISSUE #1437: GeometryPrimitives query yields random results
#### Description:

`GeometryPrimitives` query returns solids for rooms and spaces that have been deleted from the plans, but still exist in Revit. This behaviour is caused by a Revit bug that makes the elements retain their most recent volumetric geometry in the memory as they get deleted.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1437

### Test files

See https://github.com/BHoM/Revit_Toolkit/issues/1437

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by vietle-bh — APPROVED** [review]
The changes make sense 💯

**Comment by pawelbaran** [comment]
Thanks @vietle-bh - just to confirm, are you aware of any other Revit elements that would exhibit this sort of buggy behaviour? Thanks!

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by vietle-bh** [comment]
> Thanks @vietle-bh - just to confirm, are you aware of any other Revit elements that would exhibit this sort of buggy behaviour? Thanks!

I think only rooms and spaces do this. So buggy!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
