### PR TITLE
Pushing braces based on object name matching fixed

### LINKED ISSUE #1119: Pushing braces based on object name does not work
#### Description:

As in the title, pushing braces works if the name is matched against property type, but does not work in case of object type matching.

Spotted by @ssiimmoonnee

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1119

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231120%2DPushBracingBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check versioning

**Review by ssiimmoonnee — APPROVED** [review]
All good. Tested in Revit 2022

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
