### PR TITLE
Documentation issues fixed

### LINKED ISSUE #1378: Beta documentation issues
#### What is missing/incorrect?

Messed up descriptions, as spotted in https://github.com/BHoM/Revit_Toolkit/pull/1368/checks?check_run_id=14441813411

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1378

### Test files

Documentation changes only.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Documentation for param no longer in use removed. Happy to approve from code review.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, null-handling, serialisation, versioning, ready-to-merge

**Comment by FraserGreenroyd** [comment]
Neutral checks provided owing to this PR not impacting those checks, and checks about to be rerun on the deployment PR which will pick up any issues.

**Pull request merged**
